import{state,saveSettings,saveHistory}from"./state.js";import{demoAdapters}from"./adapters/demo.js";import{loadRuntime,runLive,loadRemoteHistory}from"./adapters/live.js";import{drawGauge}from"./gauges.js";import{drawLine,drawBars}from"./charts.js";import{setupUpdater}from"./updater.js";import{formatBytes,capacityTrend,growthWindow,statusClass,overallStatus}from"./usage.js";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];state.systems=demoAdapters;let remote={history:[],usage:{}};
function healthText(status,coverage=100){if(status==="bad")return"Handlungsbedarf";if(status==="warn")return"Gesund, aber mit Warnung";return coverage<100?"Gesund · Prüfung unvollständig":"Alles gesund"}
function displayValue(r){if(!r)return"—";if(r.id==="mirror")return`${Number(r.metrics?.mismatch_count??0)} Abw.`;if(Number.isFinite(r.latency))return`${r.latency} ms`;return"—"}
function renderSelectors(){$("#systemSelectors").innerHTML=state.systems.map(s=>`<label class="selector"><input type="checkbox" data-system="${s.id}" ${s.enabled?"checked":""}><div><strong>${s.name}</strong><div class="muted small">${s.kind}${s.enabled?"":" · deaktiviert"}</div></div></label>`).join("")}
function renderSystemCards(results=[]){$("#systemCards").innerHTML=state.systems.map(s=>{const r=results.find(x=>x.id===s.id),st=statusClass(r?.status);return`<div class="system-card"><span class="dot ${st}"></span><div><strong>${r?.name||s.name}</strong><div class="muted small">${r?.detail||(s.enabled?"Noch nicht geprüft":"Deaktiviert")}</div></div><strong>${displayValue(r)}</strong></div>`}).join("")}
function normalizeRemote(r){return{at:r.checked_at,checked_at:r.checked_at,health:r.health,results:r.results||[],status:r.overall_status,findings:(r.results||[]).filter(x=>["warning","critical"].includes(x.status)).map(x=>({status:statusClass(x.status),title:x.name,text:x.detail}))}}
function sameRun(a,b){const ta=Date.parse(a?.at||a?.checked_at||0),tb=Date.parse(b?.at||b?.checked_at||0);return Number.isFinite(ta)&&Number.isFinite(tb)&&Math.abs(ta-tb)<=15000&&Math.round(a?.health??-1)===Math.round(b?.health??-2)&&statusClass(a?.status)===statusClass(b?.status)}
function combinedHistory(){const rem=(remote.history||[]).map(normalizeRemote),local=state.history.filter(l=>!rem.some(r=>sameRun(l,r))),all=[...rem,...local].sort((a,b)=>Date.parse(a.at)-Date.parse(b.at));const dedup=[];for(const run of all){if(!dedup.some(x=>sameRun(x,run)))dedup.push(run)}return dedup.slice(-50)}
function latestKnownRun(){const all=combinedHistory();return all.length?all[all.length-1]:null}
function updateLastRunLabel(){const r=latestKnownRun();if(!r)return;const t=new Date(r.at||r.checked_at);if(Number.isNaN(t.getTime()))return;$("#lastRunLabel").textContent=`Letzter Lauf: ${t.toLocaleTimeString("de-DE",{hour:"2-digit",minute:"2-digit"})}`}
function activeFindings(){const run=latestKnownRun();if(!run)return[];const source=run.results?.length?run.results.filter(x=>["warning","critical","warn","bad"].includes(x.status)).map(x=>({status:statusClass(x.status),title:x.name,text:x.detail})):run.findings||[];const seen=new Set();return source.filter(x=>{const key=`${x.title}|${x.text||""}|${statusClass(x.status)}`;if(seen.has(key))return false;seen.add(key);return true})}
function renderHistory(){const all=combinedHistory();drawBars($("#historyBarChart"),all.slice(-20));const f=activeFindings();$("#findings").innerHTML=f.length?f.map(x=>`<div class="finding ${statusClass(x.status)}"><strong>${x.title}</strong><div class="muted small">${x.text||"Prüfung auffällig"}</div></div>`).join(""):`<div class="muted">Aktuell keine Fehler oder Warnungen. Frühere Befunde bleiben im Verlauf gespeichert.</div>`}
function growthLabel(hist,id,days){const g=growthWindow(hist,id,days);return g?`${g.bytes>=0?"+":""}${formatBytes(g.bytes)}`:"—"}
function renderCapacity(results=[]){const hist=combinedHistory();$("#capacityCards").innerHTML=state.systems.map(s=>{const r=results.find(x=>x.id===s.id),u=Number.isFinite(r?.usage)?r.usage:null,tr=capacityTrend(hist,s.id),forecast=tr.daysToLimit==null?"":` · Grenze ~${tr.daysToLimit} Tage`;const growth=(r?.metrics?.database_bytes)?`Wachstum: 1T ${growthLabel(hist,s.id,1)} · 7T ${growthLabel(hist,s.id,7)} · 30T ${growthLabel(hist,s.id,30)}`:"Keine realen Wachstumsdaten";return`<div class="capacity-card"><span class="dot ${statusClass(r?.status)}"></span><div><strong>${r?.name||s.name}</strong>${u!==null?`<div class="bar"><span style="width:${Math.min(100,u)}%"></span></div>`:""}<div class="muted small">${r?.capacityLabel||"Keine realen Kapazitätsdaten"} · ${growth}${forecast}</div></div><strong>${u===null?"—":u.toFixed(1)+"%"}</strong></div>`}).join("")}
function renderUsage(){const u=remote.usage||{},limit=500000,runs=Number(u.runs_31d||0),providerRequests=Number(u.requests_31d||0),p=runs/limit*100;$("#usageCards").innerHTML=`<div class="usage-card"><span class="dot ${p>=90?"bad":p>=75?"warn":"ok"}"></span><div><strong>Edge-Function-Aufrufe</strong><div class="muted small">Näherung über die tatsächlich protokollierten Prüfläufe der letzten 31 Tage</div></div><div class="kpi">${runs}</div></div><div class="usage-card"><span class="dot ok"></span><div><strong>Interne Provider-Requests</strong><div class="muted small">Zusätzliche Statusabfragen durch den System Check</div></div><div class="kpi">${providerRequests}</div></div><div class="usage-card"><span class="dot ok"></span><div><strong>Automatik / manuell</strong><div class="muted small">Automatisch ${u.auto_31d||0} · manuell/ausgewählt ${u.manual_31d||0}</div></div><div class="kpi">${runs}</div></div><div class="usage-card"><span class="dot ok"></span><div><strong>Antwortdaten</strong><div class="muted small">Nur Daten des System-Checks, nicht gesamter Provider-Traffic</div></div><div class="kpi">${formatBytes(u.response_bytes_31d||0)}</div></div><div class="usage-card"><span class="dot ${p>=90?"bad":p>=75?"warn":"ok"}"></span><div><strong>Free-Tier-Schutz</strong><div class="bar"><span style="width:${Math.min(100,p)}%"></span></div><div class="muted small">Bezugsgröße 500.000 Edge-Invocations/Monat.</div></div><strong>${p.toFixed(4)}%</strong></div>`}
function renderOverall(run){const results=run?.results||[],health=Number.isFinite(run?.health)?run.health:100,status=run?.status?statusClass(run.status):overallStatus(results),coverage=Number.isFinite(run?.coverage)?run.coverage:(results.length?Math.round(results.filter(r=>["healthy","warning","critical","ok","warn","bad"].includes(r.status)).length/results.length*100):100);$("#healthValue").textContent=Math.round(health);$("#healthText").textContent=healthText(status,coverage);$("#coverageText").textContent=`Prüfabdeckung ${coverage}%`;$("#statusOrb").dataset.state=status;$("#metricHealth").textContent=`${Math.round(health)} %`;drawGauge($("#gaugeHealth"),health,100,"Gesund",true);const core=results.find(x=>x.id==="kc_core"),future=results.find(x=>x.id==="future_academy"),mir=results.find(x=>x.id==="mirror"),mm=Number(mir?.metrics?.mismatch_count??0);drawGauge($("#gaugeCore"),core?.latency||0,5000,"ms");drawGauge($("#gaugeFuture"),future?.latency||0,5000,"ms");drawGauge($("#gaugeMirror"),Math.min(10,mm),10,"Abw.");$("#metricCore").textContent=Number.isFinite(core?.latency)?`${core.latency} ms`:"— ms";$("#metricFuture").textContent=Number.isFinite(future?.latency)?`${future.latency} ms`:"— ms";$("#metricMirror").textContent=mir?`${mm} Abw.`:"— Abw.";drawLine($("#liveLineChart"),results.filter(x=>Number.isFinite(x.latency)).map(x=>({label:x.name,value:x.latency})));renderSystemCards(results);renderCapacity(results)}
function maybeNotify(run){const st=run?.status?statusClass(run.status):overallStatus(run?.results||[]),want=(st==="bad"&&state.settings.notifyRed)||(st==="warn"&&state.settings.notifyYellow);if(want&&"Notification"in window&&Notification.permission==="granted")new Notification(`KC System Check: ${st==="bad"?"ROT":"GELB"}`,{body:healthText(st,run.coverage||100)})}
function finishRun(payload,started,trigger){const results=payload.results||[],health=Number.isFinite(payload.health)?payload.health:0,status=payload.status||overallStatus(results),findings=results.flatMap(r=>["healthy","ok","unknown","disabled"].includes(r.status)?[]:[{status:statusClass(r.status),title:r.name,text:r.detail||"Prüfung auffällig"}]),run={at:new Date().toISOString(),health,status,coverage:payload.coverage,results,findings,duration_ms:payload.duration_ms||Date.now()-started,mode:state.runtime?.mode||"demo",trigger};state.lastRun=run;state.history.push(run);state.history=state.history.slice(-50);saveHistory();updateLastRunLabel();renderOverall(run);renderHistory();maybeNotify(run);return run}
async function refreshRemote(){remote=await loadRemoteHistory(state.runtime);renderHistory();renderUsage();updateLastRunLabel();if(state.lastRun)renderCapacity(state.lastRun.results||[]);else{const latest=latestKnownRun();if(latest?.results?.length)renderCapacity(latest.results)}}
async function runChecks(ids,trigger="manual"){if(state.abortController||!ids.length)return;const controller=new AbortController();state.abortController=controller;const started=Date.now();let timer;$("#progressCard").classList.remove("hidden");$("#oneTouchBtn").disabled=true;$("#runSelectedBtn").disabled=true;$("#progressBar").style.width="8%";$("#progressText").textContent=`0 von ${ids.length}`;$("#currentStep").textContent="Prüfung wird vorbereitet";timer=setInterval(()=>$("#elapsedText").textContent=`${Math.floor((Date.now()-started)/1000)} s`,250);try{let payload;if(state.runtime?.mode==="live"&&state.runtime.apiBaseUrl){$("#progressBar").style.width="30%";$("#currentStep").textContent="Echte Systeme werden geprüft";payload=await runLive(ids,state.runtime,{signal:controller.signal,trigger});$("#progressBar").style.width="92%";$("#progressText").textContent=`${ids.length} von ${ids.length}`;}else{const results=[];const adapters=state.systems.filter(s=>ids.includes(s.id));for(let i=0;i<adapters.length;i++){if(controller.signal.aborted)throw new DOMException("Abgebrochen","AbortError");$("#currentStep").textContent=`Prüfe: ${adapters[i].name}`;const r=await adapters[i].standardCheck(controller.signal);results.push(r);$("#progressBar").style.width=`${Math.round((i+1)/adapters.length*90)}%`;$("#progressText").textContent=`${i+1} von ${adapters.length}`;}payload={results,health:Math.round(results.reduce((a,b)=>a+(b.health||0),0)/Math.max(1,results.length)),status:overallStatus(results),coverage:100}}finishRun(payload,started,trigger);$("#progressBar").style.width="100%";$("#currentStep").textContent="Abgeschlossen";await refreshRemote()}catch(e){$("#currentStep").textContent=e.name==="AbortError"?"Prüfung abgebrochen – kein Erfolgsstatus gesetzt":`Fehler: ${e.message}`}finally{clearInterval(timer);state.abortController=null;$("#oneTouchBtn").disabled=false;$("#runSelectedBtn").disabled=false;setTimeout(()=>$("#progressCard").classList.add("hidden"),2200)}}
function loadSettings(){const s=state.settings;$("#notifyYellow").checked=s.notifyYellow;$("#notifyRed").checked=s.notifyRed;$("#warnUsage").value=s.warnUsage;$("#critUsage").value=s.critUsage}
function saveSettingsFromUi(){state.settings={...state.settings,notifyYellow:$("#notifyYellow").checked,notifyRed:$("#notifyRed").checked,warnUsage:+$("#warnUsage").value,critUsage:+$("#critUsage").value};saveSettings();$("#settingsModal").classList.add("hidden")}
async function showVersion(){try{const r=await fetch(`./version.json?t=${Date.now()}`,{cache:"no-store"}),v=(await r.json()).version||"?";$("#appVersion").textContent=`v${v}`;$("#footerVersion").textContent=`KC System Check · v${v}`}catch{$("#appVersion").textContent="v?"}}
$$('.tab').forEach(b=>b.addEventListener('click',()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.view).classList.add('active')}));$("#oneTouchBtn").onclick=()=>runChecks(state.systems.filter(s=>s.enabled).map(s=>s.id),"manual");$("#runSelectedBtn").onclick=()=>runChecks($$("#systemSelectors input:checked").map(x=>x.dataset.system),"selected");$("#cancelBtn").onclick=()=>state.abortController?.abort();$("#settingsBtn").onclick=()=>$("#settingsModal").classList.remove("hidden");$("#closeSettingsBtn").onclick=()=>$("#settingsModal").classList.add("hidden");$("#saveSettingsBtn").onclick=saveSettingsFromUi;$("#notifyPermissionBtn").onclick=async()=>{if("Notification"in window)await Notification.requestPermission()};
state.runtime=await loadRuntime();await showVersion();renderSelectors();renderSystemCards();renderCapacity();renderHistory();renderOverall(state.history.at(-1));loadSettings();const live=state.runtime?.mode==="live"&&state.runtime.apiBaseUrl;$("#runtimeMode").textContent=live?"LIVE":"DEMO";$("#runtimeMode").classList.toggle("live",!!live);await refreshRemote();if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});setupUpdater();
