const $=s=>document.querySelector(s);
const SESSION_KEY='kc-system-check-admin-jwt';
let runtime=null,deviceRegistered=false,registering=false;
function endpoint(){return runtime?.apiBaseUrl?runtime.apiBaseUrl.replace(/\/kc-system-check(?:\?.*)?$/,'/kc-system-check-alerts'):''}
function registerEndpoint(){return runtime?.apiBaseUrl?runtime.apiBaseUrl.replace(/\/kc-system-check(?:\?.*)?$/,'/kc-system-check-push-register'):''}
async function loadRuntime(){for(const p of ['./config/runtime.json','./config/runtime.public.json']){try{const r=await fetch(p,{cache:'no-store'});if(r.ok)return await r.json()}catch{}}return null}
function pushText(d){if(!d)return['noch kein Zustellnachweis','warn'];const st=String(d.status||'');if(['opened','displayed'].includes(st))return[st==='opened'?'auf Gerät geöffnet':'auf Gerät angezeigt','ok'];if(['sent','delivered'].includes(st))return['vom Push-Dienst angenommen · Geräteanzeige noch nicht bestätigt','warn'];if(['retry_scheduled','dead_lettered','failed'].includes(st))return[`fehlgeschlagen${d.error_code?` · ${d.error_code}`:''}`,'bad'];return[st||'unbekannt','warn']}
function emailText(d){if(!d)return['noch kein Versandnachweis','warn'];const st=String(d.status||'');if(['delivered','opened'].includes(st))return[st==='opened'?'zugestellt und geöffnet':'zugestellt','ok'];if(st==='sent')return['an Brevo übergeben · Postfachzustellung nicht automatisch bestätigt','warn'];if(['retry_scheduled','dead_lettered','failed'].includes(st))return[`fehlgeschlagen${d.error_code?` · ${d.error_code}`:''}`,'bad'];return[st||'unbekannt','warn']}
function ensureDeviceUi(){const anchor=$('#serverPushProvider');if(!anchor||$('#localPushDeviceBox'))return;const box=document.createElement('div');box.id='localPushDeviceBox';box.className='alarm-channel-actions';box.innerHTML='<span id="localPushDeviceStatus" class="alarm-provider warn">Dieses Gerät: noch nicht bestätigt</span><button id="connectThisPushDevice" type="button" class="secondary">Dieses Gerät für Push aktivieren</button>';anchor.after(box);$('#connectThisPushDevice').addEventListener('click',()=>registerThisDevice(true))}
function setDeviceStatus(text,cls='warn'){ensureDeviceUi();const e=$('#localPushDeviceStatus');if(e){e.textContent=`Dieses Gerät: ${text}`;e.className=`alarm-provider ${cls}`}const b=$('#connectThisPushDevice');if(b){b.textContent=deviceRegistered?'Gerät registriert':'Dieses Gerät für Push aktivieren';b.disabled=registering||deviceRegistered}}
function b64ToUint8(s){const pad='='.repeat((4-s.length%4)%4),base=(s+pad).replace(/-/g,'+').replace(/_/g,'/'),raw=atob(base),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out}
async function registerThisDevice(interactive=false){if(registering||deviceRegistered)return;ensureDeviceUi();if(!('serviceWorker'in navigator)||!('PushManager'in window)){setDeviceStatus('Push wird von diesem Browser nicht unterstützt','bad');return}const token=sessionStorage.getItem(SESSION_KEY)||'';if(!token){setDeviceStatus('zuerst Admin entsperren','warn');return}let permission=Notification.permission;if(permission!=='granted'&&interactive)permission=await Notification.requestPermission();if(permission!=='granted'){setDeviceStatus(permission==='denied'?'Benachrichtigungen blockiert':'Benachrichtigung noch nicht erlaubt',permission==='denied'?'bad':'warn');return}registering=true;setDeviceStatus('Registrierung läuft …','warn');try{const ep=registerEndpoint();if(!ep)throw new Error('Registrierungs-Endpunkt fehlt');const kr=await fetch(ep,{headers:{apikey:runtime.apiToken,Authorization:`Bearer ${runtime.apiToken}`},cache:'no-store'});const ko=await kr.json().catch(()=>({}));if(!kr.ok||!ko.vapidPublicKey)throw new Error(ko.error||`VAPID HTTP ${kr.status}`);const reg=await navigator.serviceWorker.ready;let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64ToUint8(ko.vapidPublicKey)});const sr=await fetch(ep,{method:'POST',headers:{apikey:runtime.apiToken,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({subscription:sub.toJSON(),deviceLabel:'KC System Check · '+(navigator.platform||'Browser')})});const so=await sr.json().catch(()=>({}));if(!sr.ok||so.ok!==true)throw new Error(so.error||`Registrierung HTTP ${sr.status}`);deviceRegistered=true;setDeviceStatus('registriert und empfangsbereit','ok')}catch(e){setDeviceStatus(`Registrierung fehlgeschlagen · ${e.message}`,'bad')}finally{registering=false;const b=$('#connectThisPushDevice');if(b)b.disabled=deviceRegistered}}
function apply(settings){if(!settings)return;ensureDeviceUi();const p=pushText(settings.delivery?.push),e=emailText(settings.delivery?.email);const push=$('#serverPushProvider'),mail=$('#serverEmailProvider'),dp=$('#diagPushState'),de=$('#diagEmailState');if(push){push.textContent=`KC Communicator Push: ${p[0]}`;push.className=`alarm-provider ${p[1]}`}if(mail){mail.textContent=`KC Communicator E-Mail: ${e[0]}`;mail.className=`alarm-provider ${e[1]}`}if(dp)dp.textContent=`${settings.pushEnabled?'Automatik EIN':'Automatik AUS'} · ${p[0]}`;if(de)de.textContent=`${settings.emailEnabled?'Automatik EIN':'Automatik AUS'} · ${e[0]}`;const led=$('#alarmChainLed');if(led&&settings.pushEnabled&&p[1]==='warn'&&led.classList.contains('ok')){led.className='alarm-chain-led warn';led.title='Alarmkette eingeschränkt\nPush-Dienst hat angenommen, Geräteanzeige noch nicht bestätigt\nKlicken für Diagnose'}const msg=$('#alarmSaveStatus');if(msg&&/Push-Test erfolgreich/i.test(msg.textContent||'')){msg.textContent=p[1]==='ok'?'Push-Test bestätigt: Benachrichtigung wurde auf dem Gerät angezeigt.':'Push an Push-Dienst übergeben · Geräteanzeige wird noch geprüft.'}if(msg&&/E-Mail-Test erfolgreich/i.test(msg.textContent||'')){msg.textContent=e[1]==='ok'?'E-Mail-Zustellung bestätigt.':'E-Mail an Brevo übergeben · Postfachzustellung bitte kontrollieren.'}}
async function refreshProof(){try{const e=endpoint();if(!e||!runtime?.apiToken)return;const r=await fetch(e,{headers:{apikey:runtime.apiToken,Authorization:`Bearer ${runtime.apiToken}`},cache:'no-store'});if(!r.ok)return;const out=await r.json();apply(out.settings)}catch{}}
async function maybeAutoRegister(){if(deviceRegistered||registering||Notification.permission!=='granted'||!sessionStorage.getItem(SESSION_KEY))return;await registerThisDevice(false)}
async function init(){runtime=await loadRuntime();if(!runtime)return;await refreshProof();ensureDeviceUi();setDeviceStatus(Notification.permission==='granted'?'bereit zur Registrierung':Notification.permission==='denied'?'Benachrichtigungen blockiert':'noch nicht aktiviert',Notification.permission==='denied'?'bad':'warn');setInterval(refreshProof,5000);setInterval(maybeAutoRegister,2500);const obs=new MutationObserver(()=>{setTimeout(refreshProof,250);ensureDeviceUi()});obs.observe(document.body,{subtree:true,childList:true,characterData:true});document.addEventListener('click',e=>{const t=e.target;if(t instanceof Element&&t.closest('#notifyPermissionBtn'))setTimeout(()=>registerThisDevice(false),500)})}
init();
