const $=s=>document.querySelector(s);
let runtime=null;
function endpoint(){return runtime?.apiBaseUrl?runtime.apiBaseUrl.replace(/\/kc-system-check(?:\?.*)?$/,'/kc-system-check-alerts'):''}
async function loadRuntime(){for(const p of ['./config/runtime.json','./config/runtime.public.json']){try{const r=await fetch(p,{cache:'no-store'});if(r.ok)return await r.json()}catch{}}return null}
function pushText(d){if(!d)return['noch kein Zustellnachweis','warn'];const st=String(d.status||'');if(['opened','displayed'].includes(st))return[st==='opened'?'auf Gerät geöffnet':'auf Gerät angezeigt','ok'];if(['sent','delivered'].includes(st))return['vom Push-Dienst angenommen · Geräteanzeige noch nicht bestätigt','warn'];if(['retry_scheduled','dead_lettered','failed'].includes(st))return[`fehlgeschlagen${d.error_code?` · ${d.error_code}`:''}`,'bad'];return[st||'unbekannt','warn']}
function emailText(d){if(!d)return['noch kein Versandnachweis','warn'];const st=String(d.status||'');if(['delivered','opened'].includes(st))return[st==='opened'?'zugestellt und geöffnet':'zugestellt','ok'];if(st==='sent')return['an Brevo übergeben · Postfachzustellung nicht automatisch bestätigt','warn'];if(['retry_scheduled','dead_lettered','failed'].includes(st))return[`fehlgeschlagen${d.error_code?` · ${d.error_code}`:''}`,'bad'];return[st||'unbekannt','warn']}
function apply(settings){if(!settings)return;const p=pushText(settings.delivery?.push),e=emailText(settings.delivery?.email);const push=$('#serverPushProvider'),mail=$('#serverEmailProvider'),dp=$('#diagPushState'),de=$('#diagEmailState');if(push){push.textContent=`KC Communicator Push: ${p[0]}`;push.className=`alarm-provider ${p[1]}`}if(mail){mail.textContent=`KC Communicator E-Mail: ${e[0]}`;mail.className=`alarm-provider ${e[1]}`}if(dp)dp.textContent=`${settings.pushEnabled?'Automatik EIN':'Automatik AUS'} · ${p[0]}`;if(de)de.textContent=`${settings.emailEnabled?'Automatik EIN':'Automatik AUS'} · ${e[0]}`;const led=$('#alarmChainLed');if(led&&settings.pushEnabled&&p[1]==='warn'&&led.classList.contains('ok')){led.className='alarm-chain-led warn';led.title='Alarmkette eingeschränkt\nPush-Dienst hat angenommen, Geräteanzeige noch nicht bestätigt\nKlicken für Diagnose'}const msg=$('#alarmSaveStatus');if(msg&&/Push-Test erfolgreich/i.test(msg.textContent||'')){msg.textContent=p[1]==='ok'?'Push-Test bestätigt: Benachrichtigung wurde auf dem Gerät angezeigt.':'Push an Push-Dienst übergeben · Geräteanzeige wird noch geprüft.'}if(msg&&/E-Mail-Test erfolgreich/i.test(msg.textContent||'')){msg.textContent=e[1]==='ok'?'E-Mail-Zustellung bestätigt.':'E-Mail an Brevo übergeben · Postfachzustellung bitte kontrollieren.'}}
async function refreshProof(){try{const e=endpoint();if(!e||!runtime?.apiToken)return;const r=await fetch(e,{headers:{apikey:runtime.apiToken,Authorization:`Bearer ${runtime.apiToken}`},cache:'no-store'});if(!r.ok)return;const out=await r.json();apply(out.settings)}catch{}}
async function init(){runtime=await loadRuntime();if(!runtime)return;await refreshProof();setInterval(refreshProof,5000);const obs=new MutationObserver(()=>setTimeout(refreshProof,250));obs.observe(document.body,{subtree:true,childList:true,characterData:true})}
init();
