import{explainResult}from"./diagnostics.js";
const statusFrom=el=>el.querySelector(".dot.bad")?"critical":el.querySelector(".dot.warn")?"warning":null;
function inferId(name=""){if(name.includes("KC Core"))return"kc_core";if(name.includes("Future Academy"))return"future_academy";if(name.includes("Spiegel"))return"mirror";if(name.includes("GitHub"))return"github";if(name.includes("Neon"))return"neon";if(name.includes("Backblaze"))return"b2";if(name.includes("Cloudflare R2"))return"r2";if(name.includes("Oracle OCI"))return"oci";return null}
function infer(el){const title=el.querySelector("strong")?.textContent?.trim()||"System",detail=el.querySelector(".muted")?.textContent?.trim()||"Prüfung auffällig",id=inferId(title)||"unknown";const latency=Number((el.textContent.match(/(\d+)\s*ms/)||[])[1]);const mismatch=Number((el.textContent.match(/(\d+)\s*Abw/)||[])[1]);return{id,name:title,status:statusFrom(el)||"unknown",detail,latency:Number.isFinite(latency)?latency:null,metrics:{mismatch_count:Number.isFinite(mismatch)?mismatch:null}}}
function ensureModal(){if(document.querySelector("#diagnosticModal"))return;const m=document.createElement("div");m.id="diagnosticModal";m.className="diag-overlay hidden";m.innerHTML=`<div class="diag-panel"><div class="diag-head"><div><div class="diag-kicker">Ursache & Lösung</div><h2 id="diagTitle">Systemprüfung</h2></div><button id="diagClose" class="diag-close" aria-label="Schließen">✕</button></div><div class="diag-block"><strong>Warum ist das Gelb/Rot?</strong><p id="diagWhy"></p></div><div class="diag-block"><strong>Was bedeutet das?</strong><p id="diagImpact"></p></div><div class="diag-block"><strong>Was kann ich tun?</strong><ol id="diagActions"></ol></div><button id="diagAgain" class="diag-primary">Verstanden</button></div>`;document.body.appendChild(m);const close=()=>m.classList.add("hidden");m.querySelector("#diagClose").onclick=close;m.querySelector("#diagAgain").onclick=close;m.addEventListener("click",e=>{if(e.target===m)close()})}
function openDiag(el){ensureModal();const r=infer(el),x=explainResult(r),m=document.querySelector("#diagnosticModal");m.querySelector("#diagTitle").textContent=x.title;m.querySelector("#diagWhy").textContent=x.why;m.querySelector("#diagImpact").textContent=x.impact;m.querySelector("#diagActions").innerHTML=x.actions.map(a=>`<li>${a}</li>`).join("");m.classList.remove("hidden")}
function wire(){document.querySelectorAll(".system-card,.finding,.capacity-card").forEach(el=>{const st=statusFrom(el)||(el.classList.contains("warn")?"warning":el.classList.contains("bad")?"critical":null);if(!st)return;if(el.dataset.diagWired)return;el.dataset.diagWired="1";el.classList.add("diagnostic-clickable");el.setAttribute("role","button");el.setAttribute("tabindex","0");el.setAttribute("aria-label",`${el.textContent.trim()} – Details und Lösung öffnen`);el.addEventListener("click",()=>openDiag(el));el.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();openDiag(el)}})})}
const preparedNames=["Neon","Backblaze B2","Cloudflare R2","Oracle OCI Object Storage"];
function markPrepared(){document.querySelectorAll(".selector,.system-card,.capacity-card").forEach(el=>{const name=el.querySelector("strong")?.textContent||"";if(!preparedNames.some(x=>name.includes(x)))return;const muted=el.querySelector(".muted");if(!muted)return;if(/Deaktiviert|deaktiviert/.test(muted.textContent))muted.textContent=muted.textContent.replace(/Deaktiviert|deaktiviert/g,"Vorbereitet · Zugang fehlt");else if(muted.textContent.trim()==="Noch nicht geprüft")muted.textContent="Vorbereitet · Zugang fehlt"})}
function fixForecast(){document.querySelectorAll(".capacity-card .muted").forEach(el=>{const t=el.textContent;if(/Wachstum:\s*1T\s*—\s*·\s*7T\s*—\s*·\s*30T\s*—/.test(t)&&/Grenze\s*~\d+\s*Tage/.test(t))el.textContent=t.replace(/\s*·\s*Grenze\s*~\d+\s*Tage/," · Prognose noch nicht möglich")})}
const ACTIVE_KEY="kc-active-systems-v1";let selectionHydrated=false;
function selectorInputs(){return[...document.querySelectorAll('#systemSelectors input[data-system]')]}
function savedSelection(){try{const x=JSON.parse(localStorage.getItem(ACTIVE_KEY)||"null");return Array.isArray(x)?x:null}catch{return null}}
function activeIds(){return new Set(selectorInputs().filter(x=>x.checked&&!x.disabled).map(x=>x.dataset.system))}
function saveSelection(){localStorage.setItem(ACTIVE_KEY,JSON.stringify([...activeIds()]))}
function hydrateSelection(){const inputs=selectorInputs();if(selectionHydrated||!inputs.length)return;selectionHydrated=true;const saved=savedSelection();if(saved){const set=new Set(saved);inputs.forEach(x=>x.checked=set.has(x.dataset.system))}else saveSelection()}
function toggleById(id,visible){if(!id)return;document.querySelectorAll(".system-card,.capacity-card").forEach(el=>{const name=el.querySelector("strong")?.textContent||"";if(inferId(name)===id)el.classList.toggle("selection-hidden",!visible)})}
function setSelectorAvailability(){const inputs=selectorInputs(),byId=Object.fromEntries(inputs.map(x=>[x.dataset.system,x]));inputs.forEach(input=>{const row=input.closest('.selector'),prepared=preparedNames.some(n=>(row?.querySelector('strong')?.textContent||'').includes(n));if(prepared&&/Zugang fehlt/.test(row?.querySelector('.muted')?.textContent||'')){input.disabled=true;input.checked=false;row?.classList.add('dependency-disabled');row?.setAttribute('title','Der Test wird freigeschaltet, sobald der benötigte Zugang konfiguriert ist.')}});const mirror=byId.mirror;if(mirror){const core=byId.kc_core,future=byId.future_academy,hasSource=!!((core?.checked&&!core.disabled)||(future?.checked&&!future.disabled));mirror.disabled=!hasSource;if(!hasSource){mirror.checked=false;mirror.closest('.selector')?.classList.add('dependency-disabled');mirror.closest('.selector')?.setAttribute('title','Spiegelung benötigt mindestens ein aktives Quellsystem.')}else{mirror.closest('.selector')?.classList.remove('dependency-disabled');mirror.closest('.selector')?.removeAttribute('title')}}}
function applySelectionVisibility(){hydrateSelection();setSelectorAvailability();const inputs=selectorInputs();if(!inputs.length)return;const active=activeIds();for(const id of["kc_core","future_academy","mirror","neon","github","b2","r2","oci"])toggleById(id,active.has(id));const gauges={kc_core:"#gaugeCore",future_academy:"#gaugeFuture",mirror:"#gaugeMirror"};for(const[id,sel]of Object.entries(gauges)){const card=document.querySelector(sel)?.closest(".gauge-card");if(card)card.classList.toggle("selection-hidden",!active.has(id))}const one=document.querySelector("#oneTouchBtn"),selected=document.querySelector('#runSelectedBtn');if(one){one.disabled=active.size===0;one.title=active.size?`${active.size} aktive Prüfungen starten`:"Mindestens ein verfügbares System aktivieren"}if(selected){selected.disabled=active.size===0;selected.title=active.size?`${active.size} ausgewählte Prüfungen starten`:"Keine verfügbare Prüfung ausgewählt"}}
document.addEventListener("change",e=>{if(e.target?.matches?.('#systemSelectors input[data-system]')){setSelectorAvailability();saveSelection();applySelectionVisibility()}});
document.addEventListener("click",e=>{if(e.target?.closest?.("#oneTouchBtn")){const btn=e.target.closest("#oneTouchBtn");if(btn.disabled)return;e.preventDefault();e.stopImmediatePropagation();document.querySelector("#runSelectedBtn")?.click()}},true);
function injectStyle(){if(document.querySelector("#diagStyle"))return;const s=document.createElement("style");s.id="diagStyle";s.textContent=`.selection-hidden{display:none!important}.dependency-disabled{opacity:.48;filter:saturate(.55)}.dependency-disabled input{cursor:not-allowed}.diagnostic-clickable{cursor:pointer;position:relative;outline:none}.diagnostic-clickable:hover,.diagnostic-clickable:focus{border-color:#5aa7ff;box-shadow:0 0 0 2px rgba(90,167,255,.18)}.diagnostic-clickable:after{content:"Details ›";font-size:11px;color:#9ba7bd;position:absolute;right:10px;bottom:5px}.diag-overlay{position:fixed;inset:0;z-index:60;background:rgba(2,6,14,.82);display:grid;place-items:center;padding:16px}.diag-overlay.hidden{display:none}.diag-panel{width:min(560px,100%);max-height:90vh;overflow:auto;background:#0f1829;color:#f5f7fb;border:1px solid #273552;border-radius:20px;padding:18px;box-shadow:0 22px 60px rgba(0,0,0,.45)}.diag-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.diag-kicker{font-size:11px;color:#9ba7bd;text-transform:uppercase;letter-spacing:.1em}.diag-close{border:1px solid #273552;background:#17233d;color:#fff;border-radius:11px;padding:10px 12px;min-width:44px;min-height:44px}.diag-block{margin-top:15px;padding:13px;border:1px solid #273552;border-radius:13px;background:#0b1322}.diag-block p{margin:7px 0 0;color:#c6cfdd;line-height:1.45}.diag-block ol{margin:8px 0 0;padding-left:20px;color:#c6cfdd}.diag-block li{margin:7px 0}.diag-primary{width:100%;margin-top:16px;border:0;border-radius:12px;padding:13px;min-height:48px;background:#5aa7ff;color:white;font-weight:800}@media(max-width:620px){button,.selector{min-height:46px}.tabs{grid-template-columns:repeat(6,max-content)!important;scroll-snap-type:x proximity}.tab{min-width:auto!important;padding-left:14px!important;padding-right:14px!important;scroll-snap-align:start}.system-card,.capacity-card,.usage-card{padding:13px 11px;gap:9px}.diag-overlay{padding:8px}.diag-panel{border-radius:16px;padding:15px;max-height:96vh}}`;document.head.appendChild(s)}
injectStyle();ensureModal();const obs=new MutationObserver(()=>{wire();fixForecast();markPrepared();applySelectionVisibility()});obs.observe(document.body,{subtree:true,childList:true,characterData:true});wire();fixForecast();markPrepared();applySelectionVisibility();
