const ms=n=>Number.isFinite(n)?`${Math.round(n)} ms`:"nicht gemessen";
export function explainResult(r){
  const id=r?.id,status=r?.status||"unknown",m=r?.metrics||{},lat=r?.latency;
  if(status==="healthy"||status==="ok")return{title:`${r?.name||id}: alles in Ordnung`,why:r?.detail||"Die Prüfung war erfolgreich.",impact:"Kein Eingreifen erforderlich.",actions:["Keine Maßnahme nötig.","Bei Bedarf im Verlauf kontrollieren, ob der Wert stabil bleibt."]};
  if(id==="kc_core")return{title:"KC Core: Supabase-Prüfung auffällig",why:Number.isFinite(lat)?`Die Datenbank ist erreichbar, antwortet aber mit ${ms(lat)}.`:"Die Datenbank konnte nicht zuverlässig erreicht werden.",impact:"Langsame Antworten können Programme und Synchronisation verzögern.",actions:["Prüfung nach kurzer Zeit erneut starten.","Bei wiederholter Gelb-Anzeige Supabase-Status und Edge-Function-Logs prüfen.",`Der schwere Snapshot wird separat gemessen (${ms(m.snapshot_latency_ms)}); er darf den schnellen Healthcheck nicht verfälschen.`]};
  if(id==="future_academy")return{title:"Future Academy: Supabase-Prüfung auffällig",why:r?.detail||`Antwortzeit ${ms(lat)}.`,impact:"Funktionen der Future Academy könnten verzögert oder vorübergehend nicht erreichbar sein.",actions:["Prüfung wiederholen.","Bei wiederholtem Fehler Supabase-Projektstatus und die öffentliche Snapshot-RPC prüfen."]};
  if(id==="mirror")return{title:"Spiegelung: Abweichung oder veralteter Lauf",why:`Status ${m.status||"unbekannt"}, Abweichungen ${Number(m.mismatch_count??0)}, Alter ${m.age_min??"?"} min.`,impact:"Supabase und Neon könnten nicht denselben Datenstand haben.",actions:["Nächsten Mirror-Lauf abwarten oder manuell prüfen.","Bei Abweichungen Mirror-Worker und letzten Fehlereintrag untersuchen.","Nicht automatisch Daten überschreiben, bevor Quelle und Ziel eindeutig bestimmt sind."]};
  if(id==="github")return{title:"GitHub: Repository-Prüfung auffällig",why:r?.detail||"GitHub konnte nicht zuverlässig erreicht werden.",impact:"Updates oder Deployments könnten vorübergehend nicht verfügbar sein.",actions:["Internetverbindung und GitHub-Erreichbarkeit prüfen.","Prüfung später wiederholen.","Bei längerem Ausfall GitHub Actions/Pages getrennt kontrollieren."]};
  if(id==="neon")return{title:"Neon: Direktprüfung nicht verfügbar",why:r?.detail||"Es ist noch kein sicherer Read-only-Direktcheck eingerichtet.",impact:"Die Spiegelung wird überwacht, aber Neon selbst wird noch nicht separat gemessen.",actions:["Kein Fehler im laufenden Systemcheck.","Später sicheren Read-only-Healthcheck anbinden."]};
  if(id==="b2")return{title:"Backblaze B2: Prüfung deaktiviert",why:r?.detail||"B2 ist noch nicht read-only angebunden.",impact:"B2 beeinflusst den Gesamtstatus aktuell nicht.",actions:["Kein Eingreifen nötig.","Später read-only Kapazitäts- und Statusabfrage anbinden; keine Test-Uploads verwenden."]};
  return{title:`${r?.name||"System"}: Prüfung auffällig`,why:r?.detail||"Die Prüfung meldet einen auffälligen Zustand.",impact:"Der betroffene Dienst sollte kontrolliert werden.",actions:["Prüfung wiederholen.","Bei wiederholtem Auftreten den technischen Verlauf prüfen."]};
}
export function hasReliableForecast(history,id){
  const points=(history||[]).filter(run=>Number.isFinite(run?.results?.find(x=>x.id===id)?.metrics?.database_bytes)).map(run=>({t:Date.parse(run.at||run.checked_at),b:Number(run.results.find(x=>x.id===id).metrics.database_bytes)})).filter(x=>Number.isFinite(x.t)).sort((a,b)=>a.t-b.t);
  if(points.length<3)return false;
  return points[points.length-1].t-points[0].t>=24*60*60*1000;
}
