import{explainResult}from"./diagnostics.js";
const statusFrom=el=>el.querySelector(".dot.bad")?"critical":el.querySelector(".dot.warn")?"warning":null;
function infer(el){const title=el.querySelector("strong")?.textContent?.trim()||"System",detail=el.querySelector(".muted")?.textContent?.trim()||"Prüfung auffällig";let id="unknown";if(title.includes("KC Core"))id="kc_core";else if(title.includes("Future Academy"))id="future_academy";else if(title.includes("Spiegel"))id="mirror";else if(title.includes("GitHub"))id="github";else if(title.includes("Neon"))id="neon";else if(title.includes("Backblaze"))id="b2";else if(title.includes("Cloudflare R2"))id="r2";else if(title.includes("Oracle OCI"))id="oci";const latency=Number((el.textContent.match(/(\d+)\s*ms/)||[])[1]);const mismatch=Number((el.textContent.match(/(\d+)\s*Abw/)||[])[1]);return{id,name:title,status:statusFrom(el)||"unknown",detail,latency:Number.isFinite(latency)?latency:null,metrics:{mismatch_count:Number.isFinite(mismatch)?mismatch:null}}}
function ensureModal(){if(document.querySelector("#diagnosticModal"))return;const m=document.createElement("div");m.id="diagnosticModal";m.className="diag-overlay hidden";m.innerHTML=`<div class="diag-panel"><div class="diag-head"><div><div class="diag-kicker">Ursache & Lösung</div><h2 id="diagTitle">Systemprüfung</h2></div><button id="diagClose" class="diag-close" aria-label="Schließen">✕</button></div><div class="diag-block"><strong>Warum ist das Gelb/Rot?</strong><p id="diagWhy"></p></div><div class="diag-block"><strong>Was bedeutet das?</strong><p id="diagImpact"></p></div><div class="diag-block"><strong>Was kann ich tun?</strong><ol id="diagActions"></ol></div><button id="diagAgain" class="diag-primary">Verstanden</button></div>`;document.body.appendChild(m);const close=()=>m.classList.add("hidden");m.querySelector("#diagClose").onclick=close;m.querySelector("#diagAgain").onclick=close;m.addEventListener("click",e=>{if(e.target===m)close()})}
function openDiag(el){ensureModal();const r=infer(el),x=explainResult(r),m=document.querySelector("#diagnosticModal");m.querySelector("#diagTitle").textContent=x.title;m.querySelector("#diagWhy").textContent=x.why;m.querySelector("#diagImpact").textContent=x.impact;m.querySelector("#diagActions").innerHTML=x.actions.map(a=>`<li>${a}</li>`).join("");m.classList.remove("hidden")}
function wire(){document.querySelectorAll(".system-card,.finding,.capacity-card").forEach(el=>{const st=statusFrom(el)|| (el.classList.contains("warn")?"warning":el.classList.contains("bad")?"critical":null);if(!st)return;if(el.dataset.diagWired)return;el.dataset.diagWired="1";el.classList.add("diagnostic-clickable");el.setAttribute("role","button");el.setAttribute("tabindex","0");el.setAttribute("aria-label",`${el.textContent.trim()} – Details und Lösung öffnen`);el.addEventListener("click",()=>openDiag(el));el.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();openDiag(el)}})})}
const preparedNames=["Neon","Backblaze B2","Cloudflare R2","Oracle OCI Object Storage"];
function markPrepared(){document.querySelectorAll(".selector,.system-card,.capacity-card").forEach(el=>{const name=el.querySelector("strong")?.textContent||"";if(!preparedNames.some(x=>name.includes(x)))return;const muted=el.querySelector(".muted");if(!muted)return;if(/Deaktiviert|deaktiviert/.test(muted.textContent))muted.textContent=muted.textContent.replace(/Deaktiviert|deaktiviert/g,"Vorbereitet · Zugang fehlt");else if(muted.textContent.trim()==="Noch nicht geprüft")muted.textContent="Vorbereitet · Zugang fehlt"})}
function fixForecast(){document.querySelectorAll(".capacity-card .muted").forEach(el=>{const t=el.textContent;if(/Wachstum:\s*1T\s*—\s*·\s*7T\s*—\s*·\s*30T\s*—/.test(t)&&/Grenze\s*~\d+\s*Tage/.test(t))el.textContent=t.replace(/\s*·\s*Grenze\s*~\d+\s*Tage/," · Prognose noch nicht möglich")})}
function injectStyle(){if(document.querySelector("#diagStyle"))return;const s=document.createElement("style");s.id="diagStyle";s.textContent=`.diagnostic-clickable{cursor:pointer;position:relative;outline:none}.diagnostic-clickable:hover,.diagnostic-clickable:focus{border-color:#5aa7ff;box-shadow:0 0 0 2px rgba(90,167,255,.18)}.diagnostic-clickable:after{content:"Details ›";font-size:11px;color:#9ba7bd;position:absolute;right:10px;bottom:5px}.diag-overlay{position:fixed;inset:0;z-index:60;background:rgba(2,6,14,.82);display:grid;place-items:center;padding:16px}.diag-overlay.hidden{display:none}.diag-panel{width:min(560px,100%);max-height:90vh;overflow:auto;background:#0f1829;color:#f5f7fb;border:1px solid #273552;border-radius:20px;padding:18px;box-shadow:0 22px 60px rgba(0,0,0,.45)}.diag-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.diag-kicker{font-size:11px;color:#9ba7bd;text-transform:uppercase;letter-spacing:.1em}.diag-close{border:1px solid #273552;background:#17233d;color:#fff;border-radius:11px;padding:8px 10px}.diag-block{margin-top:15px;padding:13px;border:1px solid #273552;border-radius:13px;background:#0b1322}.diag-block p{margin:7px 0 0;color:#c6cfdd;line-height:1.45}.diag-block ol{margin:8px 0 0;padding-left:20px;color:#c6cfdd}.diag-block li{margin:7px 0}.diag-primary{width:100%;margin-top:16px;border:0;border-radius:12px;padding:12px;background:#5aa7ff;color:white;font-weight:800}@media(max-width:620px){.tabs{grid-template-columns:repeat(6,max-content)!important;scroll-snap-type:x proximity}.tab{min-width:auto!important;padding-left:12px!important;padding-right:12px!important;scroll-snap-align:start}}`;document.head.appendChild(s)}
injectStyle();ensureModal();const obs=new MutationObserver(()=>{wire();fixForecast();markPrepared()});obs.observe(document.body,{subtree:true,childList:true,characterData:true});wire();fixForecast();markPrepared();
