const ms=n=>Number.isFinite(n)?`${Math.round(n)} ms`:"nicht gemessen";
export function explainResult(r){
  const id=r?.id,status=r?.status||"unknown",m=r?.metrics||{},lat=r?.latency;
  if(status==="healthy"||status==="ok")return{title:`${r?.name||id}: alles in Ordnung`,why:r?.detail||"Die Prüfung war erfolgreich.",impact:"Kein Eingreifen erforderlich.",actions:["Keine Maßnahme nötig.","Bei Bedarf im Verlauf kontrollieren, ob der Wert stabil bleibt."]};
  if(id==="kc_core")return{title:"KC Core: Supabase-Prüfung auffällig",why:Number.isFinite(lat)?`Die Datenbank ist erreichbar, antwortet aber mit ${ms(lat)}.`:"Die Datenbank konnte nicht zuverlässig erreicht werden.",impact:"Langsame Antworten können Programme und Synchronisation verzögern.",actions:["Prüfung nach kurzer Zeit erneut starten.","Bei wiederholter Gelb-Anzeige Supabase-Status und Edge-Function-Logs prüfen.",`Der schwere Snapshot wird separat gemessen (${ms(m.snapshot_latency_ms)}); er darf den schnellen Healthcheck nicht verfälschen.`]};
  if(id==="future_academy")return{title:"Future Academy: Supabase-Prüfung auffällig",why:r?.detail||`Antwortzeit ${ms(lat)}.`,impact:"Funktionen der Future Academy könnten verzögert oder vorübergehend nicht erreichbar sein.",actions:["Prüfung wiederholen.","Bei wiederholtem Fehler Supabase-Projektstatus und die öffentliche Snapshot-RPC prüfen."]};
  if(id==="mirror")return{title:"Spiegelung: Abweichung oder veralteter Lauf",why:`Status ${m.status||"unbekannt"}, Abweichungen ${Number(m.mismatch_count??0)}, Alter ${m.age_min??"?"} min.`,impact:"Supabase und Neon könnten nicht denselben Datenstand haben.",actions:["Nächsten Mirror-Lauf abwarten oder manuell prüfen.","Bei Abweichungen Mirror-Worker und letzten Fehlereintrag untersuchen.","Nicht automatisch Daten überschreiben, bevor Quelle und Ziel eindeutig bestimmt sind."]};
  if(id==="backup"){
    if(status==="not_configured")return{title:"Sicherung: Zustand nicht abrufbar",why:"Ohne Zugang zur Spiegeldatenbank lässt sich nicht nachsehen, ob eine Sicherung vorliegt.",impact:"Die Sicherung läuft möglicherweise, aber niemand bestätigt es.",actions:["Zugang neon_mirror in kc_external_credentials hinterlegen."]};
    if(status==="unknown")return{title:"Sicherung: nicht prüfbar",why:r?.detail||"Die Abfrage der Sicherungsablage ist fehlgeschlagen.",impact:"Ob die letzte Sicherung gültig ist, konnte nicht festgestellt werden. Das ist kein Freispruch.",actions:["Prüfung wiederholen.","Bleibt es dabei: Neon-Zustand kontrollieren, die Ablage liegt in derselben Datenbank."]};
    const alter=Number(m.age_hours),pruef=m.verification_status;
    if(!Number.isFinite(alter))return{title:"Sicherung: es gibt keine",why:"In der Ablage steht kein einziger erfolgreich abgeschlossener Sicherungssatz.",impact:"Bei einem Datenverlust gibt es nichts zurückzuspielen. Die Spiegelung ersetzt das nicht – sie hält den aktuellen Stand, nicht den von gestern.",actions:["Den Zeitplan kc-db-immutable-backup-daily prüfen: läuft er, und kommt der Aufruf beim Sicherungsdienst an?","Einen Lauf von Hand auslösen und das Ergebnis in der Ablage nachsehen."]};
    if(pruef&&pruef!=="ok"||Number(m.verification_failed)>0)return{title:"Sicherung: die Prüfung ist nicht bestanden",why:r?.detail||"Die tägliche Prüfung des letzten Satzes meldet Fehler.",impact:"Es liegt eine Sicherung vor, aber sie ist nicht nachweislich zurückspielbar. Genau das ist der Fall, den man erst im Ernstfall merkt.",actions:["Nachsehen, welche Tabellen die Prüfung nicht bestanden haben.","Nicht auf den nächsten Lauf warten – eine ungeprüfte Sicherung ist eine Vermutung.","Bis zur Klärung den vorletzten Satz als gültigen Stand betrachten."]};
    if(alter>26)return{title:"Sicherung: zu alt",why:`Die letzte erfolgreiche Sicherung ist ${alter} Stunden alt, erwartet wird sie täglich.`,impact:alter>48?"Mehr als zwei Tage ohne Sicherung. Ein Datenverlust würde alles seit dem letzten Satz kosten.":"Ein Tageslauf ist ausgefallen.",actions:["Nachsehen, ob der nächtliche Zeitplan gelaufen ist.","Einen Lauf von Hand nachholen, statt auf die nächste Nacht zu warten."]};
    return{title:"Sicherung: auffällig",why:r?.detail||"Die Sicherung meldet einen Befund.",impact:"Der Befundtext nennt den Grund.",actions:["Den Befundtext lesen – er nennt Alter, Prüfstatus und hängende Läufe getrennt."]};
  }
  if(id==="github"){
    const funde=Array.isArray(m.secret_findings)?m.secret_findings:[];
    if(funde.length)return{title:"GitHub: Geheimnis in einer öffentlich lesbaren Datei",why:`In der mitgelieferten Laufzeitkonfiguration steht ${funde.join(" und ")}. Diese Datei kann jeder abrufen.`,impact:"Wer die Datei liest, hat den Schlüssel. Ein Austausch der Datei allein genügt nicht – der Schlüssel gilt weiter, bis er gedreht wird.",actions:["Zuerst den Schlüssel drehen, nicht zuerst die Datei ändern. Sonst bleibt der alte Schlüssel gültig.","Danach den Wert aus config/runtime.public.json entfernen und neu veröffentlichen.","Prüfen, seit wann die Datei so im Repository liegt – der Verlauf bleibt auch nach dem Löschen lesbar."]};
    if(status==="unknown")return{title:"GitHub: Konfiguration nicht prüfbar",why:r?.detail||"Die mitgelieferte Laufzeitkonfiguration war nicht abrufbar.",impact:"Ob etwas Geheimes öffentlich lesbar ist, konnte nicht geprüft werden. Das ist kein Freispruch.",actions:["Prüfung wiederholen – meist ist es eine vorübergehende Störung bei GitHub.","Bleibt es dabei: von Hand nachsehen, ob config/runtime.public.json im Hauptzweig liegt."]};
    if(m.archived)return{title:"GitHub: Repository ist archiviert",why:"Ein archiviertes Repository nimmt keine Änderungen mehr an.",impact:"Aktualisierungen und Veröffentlichungen laufen nicht mehr durch.",actions:["Archivierung aufheben, wenn weiterentwickelt werden soll.","Sonst ist der graue Zustand richtig und braucht nichts."]};
    return{title:"GitHub: Repository-Prüfung auffällig",why:r?.detail||"GitHub konnte nicht zuverlässig erreicht werden.",impact:"Updates oder Deployments könnten vorübergehend nicht verfügbar sein.",actions:["Internetverbindung und GitHub-Erreichbarkeit prüfen.","Prüfung später wiederholen.","Bei längerem Ausfall GitHub Actions/Pages getrennt kontrollieren."]};
  }
  if(id==="neon"){
    if(status==="not_configured")return{title:"Neon: Direktprüfung noch nicht scharf",why:r?.detail||"Der Zugang zur Spiegeldatenbank ist noch nicht hinterlegt.",impact:"Die Supabase→Neon-Spiegelung wird weiterhin separat überwacht; nur der Blick in die Spiegeldatenbank selbst fehlt.",actions:["Kein Datenfehler allein aufgrund dieses grauen Status.","Zugang in kc_external_credentials unter dem Namen neon_mirror hinterlegen; danach prüft der Server die Spiegeldatenbank selbst."]};
    if(!m.direct_check||m.error)return{title:"Neon: Spiegeldatenbank antwortet nicht",why:r?.detail||"Die Prüfabfrage an Neon ist fehlgeschlagen.",impact:"Der Spiegel ist im Ernstfall nicht abrufbar. Der laufende Betrieb auf Supabase ist davon nicht betroffen.",actions:["Prüfung wiederholen – die erste Abfrage weckt eine schlafende Neon-Instanz und kann in eine Zeitgrenze laufen.","Neon-Status und Compute-Zustand des Projekts kontrollieren.","Bleibt es rot: Zugang neon_mirror prüfen, die Rolle kc_monitor kann ohne Folgen für die Spiegelung neu angelegt werden."]};
    const voll=Number(m.usage_percent);
    return{title:"Neon: Spiegeldatenbank auffällig",why:r?.detail||"Die Spiegeldatenbank meldet einen Befund.",impact:Number.isFinite(voll)&&voll>=70?`Der Spiegel belegt ${voll} % des Freikontingents; läuft er voll, bricht die Spiegelung ab.`:"Der Befund betrifft die Spiegeldatenbank, nicht den laufenden Betrieb auf Supabase.",actions:["Den Befundtext lesen – er nennt die betroffene Tabelle oder Regel beim Namen.","Bei Platzmangel: alte Spiegelläufe aufräumen, bevor das Kontingent erreicht ist.","Bei Sicherheitsbefunden gilt dieselbe Regel wie auf der Supabase-Seite: ein Recht ist nur dann ein Befund, wenn nichts es deckt."]};
  }
  if(id==="b2")return{title:"Backblaze B2: Backup-Prüfung noch nicht vollständig scharf",why:r?.detail||"Es liegt noch weder ein sicherer Read-only-Statusendpunkt noch frische PC-Backup-Vault-Telemetrie vor.",impact:"B2 wird vorbereitet angezeigt und beeinflusst 100 % erst nach der Scharfstellung.",actions:["PC Backup Vault mit dem vorhandenen B2-Konto verbinden und Telemetrie aktivieren oder einen serverseitigen Read-only-Statusendpunkt hinterlegen.","Nur Lesezugriff verwenden; keine Testdatei hochladen.","Danach Bucket-Erreichbarkeit, letzter Backup-Status und Alter des letzten Backups kontrollieren."]};
  if(id==="r2")return{title:"Cloudflare R2: vorbereitet",why:r?.detail||"Für R2 ist noch kein sicherer Zugang hinterlegt.",impact:"R2 ist als möglicher Backup-/Failback-Anbieter vorbereitet, aber noch nicht Bestandteil des Gesundheitswerts.",actions:["R2-Bucket und Read-only-Zugang einrichten.","Serverseitigen Statusendpunkt hinterlegen.","Nach erfolgreicher Prüfung Anbieter aktivieren."]};
  if(id==="oci")return{title:"Oracle OCI Object Storage: vorbereitet",why:r?.detail||"OCI ist als Reserve-Anbieter angelegt, aber noch nicht konfiguriert.",impact:"OCI beeinflusst den aktuellen Betrieb und die 100-%-Anzeige noch nicht.",actions:["OCI-Bucket, Region und sicheren Read-only-Zugang einrichten.","Statusendpunkt serverseitig hinterlegen.","Erst nach erfolgreichem Verbindungstest scharfstellen."]};
  return{title:`${r?.name||"System"}: Prüfung auffällig`,why:r?.detail||"Die Prüfung meldet einen auffälligen Zustand.",impact:"Der betroffene Dienst sollte kontrolliert werden.",actions:["Prüfung wiederholen.","Bei wiederholtem Auftreten den technischen Verlauf prüfen."]};
}
export function hasReliableForecast(history,id){
  const points=(history||[]).filter(run=>Number.isFinite(run?.results?.find(x=>x.id===id)?.metrics?.database_bytes)).map(run=>({t:Date.parse(run.at||run.checked_at),b:Number(run.results.find(x=>x.id===id).metrics.database_bytes)})).filter(x=>Number.isFinite(x.t)).sort((a,b)=>a.t-b.t);
  if(points.length<3)return false;
  return points[points.length-1].t-points[0].t>=24*60*60*1000;
}
