const ms=n=>Number.isFinite(n)?`${Math.round(n)} ms`:"nicht gemessen";
export function explainResult(r){
  const id=r?.id,status=r?.status||"unknown",m=r?.metrics||{},lat=r?.latency;
  if(status==="healthy"||status==="ok")return{title:`${r?.name||id}: alles in Ordnung`,why:r?.detail||"Die Prüfung war erfolgreich.",impact:"Kein Eingreifen erforderlich.",actions:["Keine Maßnahme nötig.","Bei Bedarf im Verlauf kontrollieren, ob der Wert stabil bleibt."]};
  if(id==="kc_core")return{title:"KC Core: Supabase-Prüfung auffällig",why:Number.isFinite(lat)?`Die Datenbank ist erreichbar, antwortet aber mit ${ms(lat)}.`:"Die Datenbank konnte nicht zuverlässig erreicht werden.",impact:"Langsame Antworten können Programme und Synchronisation verzögern.",actions:["Prüfung nach kurzer Zeit erneut starten.","Bei wiederholter Gelb-Anzeige Supabase-Status und Edge-Function-Logs prüfen.",`Der schwere Snapshot wird separat gemessen (${ms(m.snapshot_latency_ms)}); er darf den schnellen Healthcheck nicht verfälschen.`]};
  if(id==="future_academy")return{title:"Future Academy: Supabase-Prüfung auffällig",why:r?.detail||`Antwortzeit ${ms(lat)}.`,impact:"Funktionen der Future Academy könnten verzögert oder vorübergehend nicht erreichbar sein.",actions:["Prüfung wiederholen.","Bei wiederholtem Fehler Supabase-Projektstatus und die öffentliche Snapshot-RPC prüfen."]};
  if(id==="mirror")return{title:"Spiegelung: Abweichung oder veralteter Lauf",why:`Status ${m.status||"unbekannt"}, Abweichungen ${Number(m.mismatch_count??0)}, Alter ${m.age_min??"?"} min.`,impact:"Supabase und Neon könnten nicht denselben Datenstand haben.",actions:["Nächsten Mirror-Lauf abwarten oder manuell prüfen.","Bei Abweichungen Mirror-Worker und letzten Fehlereintrag untersuchen.","Nicht automatisch Daten überschreiben, bevor Quelle und Ziel eindeutig bestimmt sind."]};
  if(id==="github")return{title:"GitHub: Repository-Prüfung auffällig",why:r?.detail||"GitHub konnte nicht zuverlässig erreicht werden.",impact:"Updates oder Deployments könnten vorübergehend nicht verfügbar sein.",actions:["Internetverbindung und GitHub-Erreichbarkeit prüfen.","Prüfung später wiederholen.","Bei längerem Ausfall GitHub Actions/Pages getrennt kontrollieren."]};
  if(id==="neon")return{title:"Neon: Direktprüfung noch nicht scharf",why:r?.detail||"Der direkte Read-only-Zugang ist noch nicht hinterlegt.",impact:"Die Supabase→Neon-Spiegelung wird weiterhin separat und vollständig überwacht; nur der unabhängige Neon-Erreichbarkeitstest fehlt.",actions:["Kein Datenfehler allein aufgrund dieses grauen Status.","Sicheren Read-only-Health-Endpunkt hinterlegen; danach wird Neon automatisch scharfgeschaltet."]};
  if(id==="b2")return{title:"Backblaze B2: Backup-Prüfung noch nicht vollständig scharf",why:r?.detail||"Es liegt noch weder ein sicherer Read-only-Statusendpunkt noch frische PC-Backup-Vault-Telemetrie vor.",impact:"B2 wird vorbereitet angezeigt und beeinflusst 100 % erst nach der Scharfstellung.",actions:["PC Backup Vault mit dem vorhandenen B2-Konto verbinden und Telemetrie aktivieren oder einen serverseitigen Read-only-Statusendpunkt hinterlegen.","Nur Lesezugriff verwenden; keine Testdatei hochladen.","Danach Bucket-Erreichbarkeit, letzter Backup-Status und Alter des letzten Backups kontrollieren."]};
  if(id==="r2")return{title:"Cloudflare R2: vorbereitet",why:r?.detail||"Für R2 ist noch kein sicherer Zugang hinterlegt.",impact:"R2 ist als möglicher Backup-/Failback-Anbieter vorbereitet, aber noch nicht Bestandteil des Gesundheitswerts.",actions:["R2-Bucket und Read-only-Zugang einrichten.","Serverseitigen Statusendpunkt hinterlegen.","Nach erfolgreicher Prüfung Anbieter aktivieren."]};
  if(id==="oci")return{title:"Oracle OCI Object Storage: vorbereitet",why:r?.detail||"OCI ist als Reserve-Anbieter angelegt, aber noch nicht konfiguriert.",impact:"OCI beeinflusst den aktuellen Betrieb und die 100-%-Anzeige noch nicht.",actions:["OCI-Bucket, Region und sicheren Read-only-Zugang einrichten.","Statusendpunkt serverseitig hinterlegen.","Erst nach erfolgreichem Verbindungstest scharfstellen."]};
  return{title:`${r?.name||"System"}: Prüfung auffällig`,why:r?.detail||"Die Prüfung meldet einen auffälligen Zustand.",impact:"Der betroffene Dienst sollte kontrolliert werden.",actions:["Prüfung wiederholen.","Bei wiederholtem Auftreten den technischen Verlauf prüfen."]};
}
export function hasReliableForecast(history,id){
  const points=(history||[]).filter(run=>Number.isFinite(run?.results?.find(x=>x.id===id)?.metrics?.database_bytes)).map(run=>({t:Date.parse(run.at||run.checked_at),b:Number(run.results.find(x=>x.id===id).metrics.database_bytes)})).filter(x=>Number.isFinite(x.t)).sort((a,b)=>a.t-b.t);
  if(points.length<3)return false;
  return points[points.length-1].t-points[0].t>=24*60*60*1000;
}
