const STORE='kc-early-warning-v1',MAX=12;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function load(){try{return JSON.parse(localStorage.getItem(STORE)||'{}')||{}}catch{return{}}}
function save(v){try{localStorage.setItem(STORE,JSON.stringify(v))}catch{}}
function key(el,i){return(el.dataset.system||el.dataset.id||el.querySelector('strong')?.textContent||`metric-${i}`).trim().toLowerCase().slice(0,80)}
function metric(el){const t=(el.textContent||'').replace(/,/g,'.'),m=t.match(/(\d+(?:\.\d+)?)\s*(ms|%|mb|gb)\b/i);return m?{value:Number(m[1]),unit:m[2].toLowerCase()}:null}
function collect(){return $$('#live .live-kpi,#live .live-device,#capacity .card,#usage .card,.gauge-card').map((el,i)=>({el,k:key(el,i),m:metric(el)})).filter(x=>x.m&&Number.isFinite(x.m.value))}
function sample(){const db=load(),now=Date.now();for(const x of collect()){const a=db[x.k]||[];const last=a[a.length-1];if(!last||now-last.t>45000||last.v!==x.m.value)a.push({t:now,v:x.m.value,u:x.m.unit});db[x.k]=a.slice(-MAX)}save(db);return db}
function trend(a){if(!a||a.length<4)return null;const recent=a.slice(-4),first=recent[0].v,last=recent.at(-1).v;if(first===0)return null;const pct=(last-first)/Math.abs(first)*100;const rising=recent.every((x,i)=>i===0||x.v>=recent[i-1].v);if(rising&&pct>=20)return{level:'warn',text:`steigend +${Math.round(pct)} % in ${recent.length} Messungen`};if(pct>=10)return{level:'watch',text:`Tendenz +${Math.round(pct)} %`};return null}
function warnings(db){return collect().map(x=>({x,t:trend(db[x.k])})).filter(v=>v.t).sort((a,b)=>(a.t.level==='warn'?0:1)-(b.t.level==='warn'?0:1))}
function styles(){if($('#kcEarlyStyles'))return;const s=document.createElement('style');s.id='kcEarlyStyles';s.textContent='.kc-early{margin:8px 0;padding:8px 10px;border:1px solid #a77a25;border-radius:10px;background:#19170f}.kc-early-row{padding:4px 0}.kc-early-warn{color:#ffd166;font-weight:800}';document.head.appendChild(s)}
function render(){styles();const db=sample(),all=warnings(db),w=all.filter(v=>v.t.level==='warn'),old=$('#kcEarlyWarning');globalThis.KC_EARLY_WARNING_STATE={observed:all.length,actionable:w.length,at:new Date().toISOString()};if(!w.length){old?.remove();return}const host=old||document.createElement('div');host.id='kcEarlyWarning';host.className='kc-early';host.innerHTML=`<strong>Frühwarnung · ${w.length} relevante${w.length===1?'r':' Trends'}</strong><div class="muted small">Noch keine Störung · Entwicklung gezielt beobachten.</div>${w.slice(0,3).map(({x,t})=>`<div class="kc-early-row"><span class="kc-early-warn">BEOBACHTEN</span> · ${(x.el.querySelector('strong')?.textContent||x.k).trim()} · ${t.text}</div>`).join('')}`;if(!old)($('.tabs')||$('#kcQualityReport')||$('.hero'))?.before(host)}
let q=false;function schedule(){if(q)return;q=true;setTimeout(()=>{q=false;render()},500)}
render();new MutationObserver(schedule).observe(document.documentElement,{subtree:true,childList:true,characterData:true});
