import{loadLeitstand}from"./adapters/live.js";
const $=s=>document.querySelector(s);
const eur=c=>Number.isFinite(Number(c))?new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format(Number(c)/100):"—";
const ageSeconds=t=>{const n=Date.parse(t||"");return Number.isFinite(n)?Math.max(0,Math.round((Date.now()-n)/1000)):null};
const ageText=s=>s==null?"nie":s<60?`vor ${s} s`:s<3600?`vor ${Math.round(s/60)} min`:s<86400?`vor ${Math.round(s/3600)} h`:`vor ${Math.round(s/86400)} T`;
const operational=id=>/(kasse|markt|pos|manager)/i.test(id||"");
function hbState(h,thresholds={}){const age=ageSeconds(h?.measured_at||h?.received_at),warn=Number(thresholds.heartbeat_warn_seconds||90),crit=Number(thresholds.heartbeat_critical_seconds||180);if(age==null)return{cls:"idle",label:"Noch nie gemeldet",age};if(!operational(h.program_id)&&age>crit)return{cls:"idle",label:`Nicht aktiv · ${ageText(age)}`,age};if(age>crit)return{cls:"bad",label:`Keine Meldung ${ageText(age)}`,age};if(age>warn)return{cls:"warn",label:`Heartbeat verspätet · ${ageText(age)}`,age};return{cls:"ok",label:`Online · ${ageText(age)}`,age}}
function heartbeatName(h){const id=String(h.program_id||"").toLowerCase();if(id.includes("manager"))return"PC Manager";if(id.includes("kasse")||id.includes("markt")||id.includes("pos"))return`Kasse · ${h.instance_id||"Instanz"}`;if(id==="kc-dp2")return"KC DP2";if(id==="kicc")return"KC Communication / KICC";return h.program_id||"KC Programm"}
function placeholder(name,text){return`<div class="live-device"><span class="dot idle"></span><div><strong>${name}</strong><div class="muted small">${text}</div></div><span class="live-tag">vorbereitet</span></div>`}
function renderPrograms(data){const hs=data.heartbeats||[],thresholds=data.thresholds||{},sorted=[...hs].sort((a,b)=>Date.parse(b.measured_at||0)-Date.parse(a.measured_at||0)),pos=sorted.filter(h=>/(kasse|markt|pos)/i.test(h.program_id||"")),manager=sorted.filter(h=>/manager/i.test(h.program_id||""));let html=sorted.map(h=>{const st=hbState(h,thresholds),q=Number(h.queue_depth||0),err=Number(h.error_count||0),extra=[h.version?`v${h.version}`:"",q?`Queue ${q}`:"",err?`${err} Fehler`:""].filter(Boolean).join(" · ");return`<div class="live-device ${st.cls==='bad'?'live-alert':''}"><span class="dot ${st.cls}"></span><div><strong>${heartbeatName(h)}</strong><div class="muted small">${st.label}${extra?` · ${extra}`:""}</div></div><span class="live-tag">${h.status||"—"}</span></div>`}).join("");if(pos.length<2)for(let i=pos.length;i<2;i++)html+=placeholder(`Kasse ${i+1}`,"Heartbeat-Anbindung in der Marktkasse vorbereitet");if(!manager.length)html+=placeholder("PC Manager","Heartbeat-Anbindung im Manager vorbereitet");$("#livePrograms").innerHTML=html||placeholder("KC Programme","Noch keine Heartbeats vorhanden")}
function renderSummary(data){const hs=data.heartbeats||[],th=data.thresholds||{},active=hs.map(h=>({h,s:hbState(h,th)})),pos=active.filter(x=>/(kasse|markt|pos)/i.test(x.h.program_id||"")),manager=active.filter(x=>/manager/i.test(x.h.program_id||"")),posOnline=pos.filter(x=>x.s.cls==="ok").length,managerOnline=manager.some(x=>x.s.cls==="ok"),queue=active.filter(x=>["ok","warn"].includes(x.s.cls)).reduce((n,x)=>n+Number(x.h.queue_depth||0),0),errors=active.filter(x=>["ok","warn","bad"].includes(x.s.cls)).reduce((n,x)=>n+Number(x.h.error_count||0),0);const kpis=[{label:"Kassen",value:pos.length?`${posOnline}/${Math.max(2,pos.length)}`:"0/2",sub:pos.length?"online":"Anbindung vorbereitet",cls:pos.some(x=>x.s.cls==="bad")?"bad":pos.some(x=>x.s.cls==="warn")?"warn":posOnline?"ok":"idle"},{label:"PC Manager",value:manager.length?(managerOnline?"ONLINE":"OFFLINE"):"—",sub:manager.length?manager.map(x=>x.s.label).join(", "):"Anbindung vorbereitet",cls:manager.length?(managerOnline?"ok":"bad"):"idle"},{label:"Sync-Queue",value:String(queue),sub:queue?"Datensätze warten":"keine wartenden Datensätze",cls:queue>20?"bad":queue>0?"warn":"ok"},{label:"Fehlerzähler",value:String(errors),sub:"aus aktiven Heartbeats",cls:errors>10?"bad":errors>0?"warn":"ok"}];$("#liveKpis").innerHTML=kpis.map(k=>`<div class="live-kpi"><span class="dot ${k.cls}"></span><div class="muted small">${k.label}</div><div class="kpi">${k.value}</div><div class="muted small">${k.sub}</div></div>`).join("")}
function renderSales(data){const sales=data.sales||[],today=sales.filter(x=>x.event_type==="sale"),sum=today.reduce((n,x)=>n+Number(x.amount_cents||0),0);$("#liveSalesSummary").textContent=sales.length?`${today.length} Verkäufe · ${eur(sum)} · letzte 24 h`:`Live-Buchungsfeed vorbereitet · noch keine Kassenereignisse empfangen`;$("#liveSales").innerHTML=sales.length?sales.slice(0,20).map(x=>`<div class="live-sale"><div><strong>${x.register_id}</strong><div class="muted small">${new Date(x.occurred_at).toLocaleTimeString("de-DE",{hour:"2-digit",minute:"2-digit",second:"2-digit"})} · ${x.event_type}${x.payment_type?` · ${x.payment_type}`:""}${Number.isFinite(Number(x.item_count))?` · ${x.item_count} Artikel`:""}</div></div><div class="live-sale-value">${x.event_type==="sale"?eur(x.amount_cents):x.event_type.toUpperCase()}<div class="muted small">${x.sync_state||""}</div></div></div>`).join(""):`<div class="live-empty"><strong>Live-Monitor ist bereit.</strong><div class="muted small">Sobald die Online-Kassen die anonymisierte Technik-Telemetrie senden, erscheinen hier Buchungszeit, Kasse, Betrag, Zahlungsart, Artikelanzahl und Sync-Status. Keine Kundendaten und keine Artikeldetails.</div></div>`}
function renderFlows(data){const flows=data.flows||[];$("#liveFlows").innerHTML=flows.length?flows.slice(0,12).map(x=>`<div class="live-flow"><span class="dot ${String(x.status).toLowerCase().includes("error")?"bad":"ok"}"></span><div><strong>${x.source_id||x.program_id||"Quelle"} → ${x.target_id||"Ziel"}</strong><div class="muted small">${x.flow_type||"Datenfluss"} · ${x.event_count||0} Ereignisse · ${ageText(ageSeconds(x.measured_at))}</div></div></div>`).join(""):`<div class="muted small">Noch keine Flow-Telemetrie. Der Bereich wird automatisch aktiv, sobald Programme Datenflüsse melden.</div>`}
function render(data){renderSummary(data);renderPrograms(data);renderSales(data);renderFlows(data);const t=new Date(data.checked_at||Date.now());$("#liveLastUpdate").textContent=data.error?`Fehler: ${data.error}`:`Aktualisiert ${t.toLocaleTimeString("de-DE",{hour:"2-digit",minute:"2-digit",second:"2-digit"})} · Server ${data.server_latency_ms??"—"} ms`}
export function setupLeitstand(runtime){let running=false,timer=null,controller=null;async function refresh(){if(running)return;running=true;const btn=$("#liveRefreshBtn");if(btn){btn.disabled=true;btn.textContent="Aktualisiere …"}controller=new AbortController();try{render(await loadLeitstand(runtime,{signal:controller.signal}))}finally{running=false;controller=null;if(btn){btn.disabled=false;btn.textContent="Jetzt aktualisieren"}}}function schedule(){clearInterval(timer);timer=setInterval(()=>{if(!document.hidden&&$("#live")?.classList.contains("active"))refresh()},30000)}$("#liveRefreshBtn")?.addEventListener("click",refresh);document.addEventListener("visibilitychange",()=>{if(!document.hidden&&$("#live")?.classList.contains("active"))refresh()});document.querySelector('[data-view="live"]')?.addEventListener("click",refresh);refresh();schedule();return()=>{clearInterval(timer);controller?.abort()}}
