const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const BAD_WORDS=["störung","fehler aktuell","critical","handlungsbedarf"];
const WARN_WORDS=["veraltet","historisch","unbekannt","anbindung vorbereitet","telemetrie vorbereitet","nicht aktiv","warnung"];
function txt(el){return(el?.textContent||"").replace(/\s+/g," ").trim().toLowerCase()}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function severity(el){const t=txt(el);return BAD_WORDS.some(w=>t.includes(w))?"bad":WARN_WORDS.some(w=>t.includes(w))?"warn":"ok"}
function candidateCards(){return $$("#live .live-device,#live .live-kpi,#findings .finding").filter(x=>severity(x)!=="ok")}
function ensureStyles(){if($("#kcQualityStyles"))return;const s=document.createElement("style");s.id="kcQualityStyles";s.textContent=`.kc-quality-strip{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px}.kc-quality-btn{min-height:42px;border:1px solid var(--line);border-radius:10px;background:var(--card2);color:#fff;padding:8px 10px;font-weight:700}.kc-quality-box{margin-top:10px;padding:10px;border:1px solid var(--line);border-radius:12px;background:#0d1728}.kc-quality-row{display:flex;justify-content:space-between;gap:12px;padding:7px 0;border-bottom:1px solid var(--line)}.kc-quality-row:last-child{border-bottom:0}.kc-quality-bad{color:#ff7b7b}.kc-quality-warn{color:#ffd166}@media(max-width:620px){.kc-quality-btn{width:100%}.kc-quality-row{display:block}}`;document.head.appendChild(s)}
function openReport(){const items=candidateCards();const host=$("#kcQualityReport")||document.createElement("div");host.id="kcQualityReport";host.className="kc-quality-box";host.innerHTML=`<strong>Aktuelle Auffälligkeiten: ${items.length}</strong>${items.length?items.slice(0,12).map((x,i)=>`<div class="kc-quality-row"><span>${i+1}. ${esc((x.querySelector("strong")?.textContent||x.textContent).trim().slice(0,80))}</span><b class="kc-quality-${severity(x)}">${severity(x)==="bad"?"AKTUELL":"PRÜFEN"}</b></div>`).join(""):`<div class="muted small">Keine aktuelle Auffälligkeit aus den sichtbaren LIVE-/Befunddaten erkannt.</div>`}`;const hero=$(".hero");if(!host.isConnected)hero?.after(host);host.scrollIntoView({behavior:"smooth",block:"nearest"})}
function install(){ensureStyles();const hero=$(".hero");if(!hero||$("#kcQualityStrip"))return;const strip=document.createElement("div");strip.id="kcQualityStrip";strip.className="kc-quality-strip";const b=document.createElement("button");b.type="button";b.className="kc-quality-btn";b.textContent="Auffälligkeiten zusammenfassen";b.onclick=openReport;strip.appendChild(b);hero.appendChild(strip)}
install();new MutationObserver(()=>install()).observe(document.documentElement,{subtree:true,childList:true});
