const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const BAD_WORDS=["störung","fehler aktuell","critical","handlungsbedarf"];
const WARN_WORDS=["veraltet","historisch","unbekannt","anbindung vorbereitet","telemetrie vorbereitet","nicht aktiv","warnung"];
const PRIORITY=[[/datenbank|supabase|neon|sync|spiegelung/,100,"Datenweg prüfen"],[/kasse|buchung|manager/,90,"Betriebssystem prüfen"],[/backup|sicherung/,75,"Sicherung prüfen"],[/kommunikation|push|e-mail|email/,65,"Kommunikation prüfen"],[/veraltet|heartbeat|telemetrie/,45,"Daten aktualisieren"],[/historisch|vorbereitet|unbekannt/,25,"Anbindung prüfen"]];
function txt(el){return(el?.textContent||"").replace(/\s+/g," ").trim().toLowerCase()}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function severity(el){const t=txt(el);return BAD_WORDS.some(w=>t.includes(w))?"bad":WARN_WORDS.some(w=>t.includes(w))?"warn":"ok"}
function priority(el){const t=txt(el),sev=severity(el),rule=PRIORITY.find(([r])=>r.test(t));return{score:(sev==="bad"?200:100)+(rule?.[1]||10),action:rule?.[2]||(sev==="bad"?"Störung prüfen":"Status prüfen")}}
function candidateCards(){return $$("#live .live-device,#live .live-kpi,#findings .finding").filter(x=>severity(x)!=="ok")}
function sortedCards(){return candidateCards().map(el=>({el,...priority(el)})).sort((a,b)=>b.score-a.score)}
function counts(){const a=candidateCards();return{all:a,bad:a.filter(x=>severity(x)==="bad"),warn:a.filter(x=>severity(x)==="warn")}}
function ensureStyles(){if($("#kcQualityStyles"))return;const s=document.createElement("style");s.id="kcQualityStyles";s.textContent=`.kc-quality-strip{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px}.kc-quality-btn{min-height:42px;border:1px solid var(--line);border-radius:10px;background:var(--card2);color:#fff;padding:8px 10px;font-weight:700}.kc-quality-badge{display:inline-flex;align-items:center;justify-content:center;min-width:26px;margin-left:6px;padding:2px 7px;border-radius:999px;background:#0d1728;border:1px solid var(--line)}.kc-quality-btn[data-state=bad]{border-color:var(--bad)}.kc-quality-btn[data-state=warn]{border-color:var(--warn)}.kc-quality-box{margin-top:10px;padding:10px;border:1px solid var(--line);border-radius:12px;background:#0d1728}.kc-quality-row{display:grid;grid-template-columns:38px 1fr auto;gap:10px;align-items:center;padding:8px 0;border-bottom:1px solid var(--line)}.kc-quality-row:last-child{border-bottom:0}.kc-quality-prio{font-size:12px;font-weight:800;text-align:center;border:1px solid var(--line);border-radius:8px;padding:4px}.kc-quality-action{font-size:11px;color:var(--muted);margin-top:3px}.kc-quality-bad{color:#ff7b7b}.kc-quality-warn{color:#ffd166}.kc-quality-filter{display:flex;gap:6px;flex-wrap:wrap;margin:8px 0}.kc-quality-filter button{min-height:38px}.kc-quality-filter button.active{outline:2px solid var(--accent)}@media(max-width:620px){.kc-quality-btn{width:100%}.kc-quality-row{grid-template-columns:34px 1fr}.kc-quality-row>b{grid-column:2}}`;document.head.appendChild(s)}
function renderReport(filter="all"){const c=counts(),ranked=sortedCards().filter(x=>filter==="bad"?severity(x.el)==="bad":filter==="warn"?severity(x.el)==="warn":true),host=$("#kcQualityReport")||document.createElement("div");host.id="kcQualityReport";host.className="kc-quality-box";host.innerHTML=`<strong>Was muss ich zuerst tun?</strong><div class="muted small">Priorität automatisch nach Störungsschwere und betroffener Funktion. Es wird nichts automatisch repariert.</div><div class="kc-quality-filter"><button class="secondary ${filter==="all"?"active":""}" data-qf="all">Alle ${c.all.length}</button><button class="secondary ${filter==="bad"?"active":""}" data-qf="bad">Aktuell ${c.bad.length}</button><button class="secondary ${filter==="warn"?"active":""}" data-qf="warn">Prüfen ${c.warn.length}</button></div>${ranked.length?ranked.slice(0,12).map((x,i)=>`<div class="kc-quality-row"><span class="kc-quality-prio">P${i+1}</span><span>${esc((x.el.querySelector("strong")?.textContent||x.el.textContent).trim().slice(0,100))}<div class="kc-quality-action">Nächster Schritt: ${esc(x.action)}</div></span><b class="kc-quality-${severity(x.el)}">${severity(x.el)==="bad"?"AKTUELL":"PRÜFEN"}</b></div>`).join(""):`<div class="muted small">Für diesen Filter liegt keine sichtbare Auffälligkeit vor.</div>`}`;if(!host.isConnected)$(".hero")?.after(host);host.querySelectorAll("[data-qf]").forEach(b=>b.onclick=()=>renderReport(b.dataset.qf));return host}
function openReport(){renderReport().scrollIntoView({behavior:"smooth",block:"nearest"})}
function refreshBadge(){const b=$("#kcQualityBtn");if(!b)return;const c=counts(),state=c.bad.length?"bad":c.warn.length?"warn":"ok";b.dataset.state=state;b.innerHTML=`Was muss ich zuerst tun? <span class="kc-quality-badge">${c.all.length}</span>`}
function install(){ensureStyles();const hero=$(".hero");if(!hero)return;if(!$("#kcQualityStrip")){const strip=document.createElement("div");strip.id="kcQualityStrip";strip.className="kc-quality-strip";const b=document.createElement("button");b.id="kcQualityBtn";b.type="button";b.className="kc-quality-btn";b.onclick=openReport;strip.appendChild(b);hero.appendChild(strip)}refreshBadge()}
let queued=false;function schedule(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;install();if($("#kcQualityReport"))renderReport($("#kcQualityReport .active")?.dataset.qf||"all")})}
install();new MutationObserver(schedule).observe(document.documentElement,{subtree:true,childList:true,characterData:true});
