const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const BAD_WORDS=["störung","fehler aktuell","critical","handlungsbedarf"];
const WARN_WORDS=["veraltet","historisch","unbekannt","anbindung vorbereitet","telemetrie vorbereitet","nicht aktiv","warnung"];
function txt(el){return(el?.textContent||"").replace(/\s+/g," ").trim().toLowerCase()}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function severity(el){const t=txt(el);return BAD_WORDS.some(w=>t.includes(w))?"bad":WARN_WORDS.some(w=>t.includes(w))?"warn":"ok"}
function candidateCards(){return $$("#live .live-device,#live .live-kpi,#findings .finding").filter(x=>severity(x)!=="ok")}
function counts(){const a=candidateCards();return{all:a,bad:a.filter(x=>severity(x)==="bad"),warn:a.filter(x=>severity(x)==="warn")}}
function ensureStyles(){if($("#kcQualityStyles"))return;const s=document.createElement("style");s.id="kcQualityStyles";s.textContent=`.kc-quality-strip{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px}.kc-quality-btn{min-height:42px;border:1px solid var(--line);border-radius:10px;background:var(--card2);color:#fff;padding:8px 10px;font-weight:700}.kc-quality-badge{display:inline-flex;align-items:center;justify-content:center;min-width:26px;margin-left:6px;padding:2px 7px;border-radius:999px;background:#0d1728;border:1px solid var(--line)}.kc-quality-btn[data-state=bad]{border-color:var(--bad)}.kc-quality-btn[data-state=warn]{border-color:var(--warn)}.kc-quality-box{margin-top:10px;padding:10px;border:1px solid var(--line);border-radius:12px;background:#0d1728}.kc-quality-row{display:flex;justify-content:space-between;gap:12px;padding:7px 0;border-bottom:1px solid var(--line)}.kc-quality-row:last-child{border-bottom:0}.kc-quality-bad{color:#ff7b7b}.kc-quality-warn{color:#ffd166}.kc-quality-filter{display:flex;gap:6px;flex-wrap:wrap;margin:8px 0}.kc-quality-filter button{min-height:38px}.kc-quality-filter button.active{outline:2px solid var(--accent)}@media(max-width:620px){.kc-quality-btn{width:100%}.kc-quality-row{display:block}}`;document.head.appendChild(s)}
function renderReport(filter="all"){const c=counts(),items=filter==="bad"?c.bad:filter==="warn"?c.warn:c.all,host=$("#kcQualityReport")||document.createElement("div");host.id="kcQualityReport";host.className="kc-quality-box";host.innerHTML=`<strong>Auffälligkeiten: ${c.all.length} · aktuell ${c.bad.length} · prüfen ${c.warn.length}</strong><div class="kc-quality-filter"><button class="secondary ${filter==="all"?"active":""}" data-qf="all">Alle</button><button class="secondary ${filter==="bad"?"active":""}" data-qf="bad">Aktuell</button><button class="secondary ${filter==="warn"?"active":""}" data-qf="warn">Prüfen</button></div>${items.length?items.slice(0,12).map((x,i)=>`<div class="kc-quality-row"><span>${i+1}. ${esc((x.querySelector("strong")?.textContent||x.textContent).trim().slice(0,100))}</span><b class="kc-quality-${severity(x)}">${severity(x)==="bad"?"AKTUELL":"PRÜFEN"}</b></div>`).join(""):`<div class="muted small">Für diesen Filter liegt keine sichtbare Auffälligkeit vor.</div>`}`;if(!host.isConnected)$(".hero")?.after(host);host.querySelectorAll("[data-qf]").forEach(b=>b.onclick=()=>renderReport(b.dataset.qf));return host}
function openReport(){renderReport().scrollIntoView({behavior:"smooth",block:"nearest"})}
function refreshBadge(){const b=$("#kcQualityBtn");if(!b)return;const c=counts(),state=c.bad.length?"bad":c.warn.length?"warn":"ok";b.dataset.state=state;b.innerHTML=`Auffälligkeiten zusammenfassen <span class="kc-quality-badge">${c.all.length}</span>`}
function install(){ensureStyles();const hero=$(".hero");if(!hero)return;if(!$("#kcQualityStrip")){const strip=document.createElement("div");strip.id="kcQualityStrip";strip.className="kc-quality-strip";const b=document.createElement("button");b.id="kcQualityBtn";b.type="button";b.className="kc-quality-btn";b.onclick=openReport;strip.appendChild(b);hero.appendChild(strip)}refreshBadge()}
let queued=false;function schedule(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;install();if($("#kcQualityReport"))renderReport($("#kcQualityReport .active")?.dataset.qf||"all")})}
install();new MutationObserver(schedule).observe(document.documentElement,{subtree:true,childList:true,characterData:true});
