const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const PROFILE={name:'KC Verification Profile',version:'2026.09',asvs:'5.0.0',wstg:'stable'};
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function enabledCount(){return $$('#systemSelectors input[type="checkbox"]:checked:not(:disabled)').length}
function evaluatedCount(){return $$('#systemCards .dot.ok,#systemCards .dot.warn,#systemCards .dot.bad').length}
function liveMode(){return $('#runtimeMode')?.textContent?.trim()==='LIVE'}
function securePage(){return location.protocol==='https:'||location.hostname==='localhost'}
async function runtimeSecurity(){try{const r=await fetch('./config/runtime.json',{cache:'no-store'});if(!r.ok)return{https:false,publicOnly:false};const cfg=await r.json(),url=String(cfg.apiBaseUrl||'');const token=String(cfg.apiToken||'');return{https:/^https:\/\//i.test(url),publicOnly:!/(service[_-]?role|secret|private)/i.test(token)}}catch{return{https:false,publicOnly:false}}}
function state(){const defined=enabledCount(),evaluated=Math.min(evaluatedCount(),defined||Infinity),coverage=defined?Math.round(evaluated/defined*100):0;return{defined,evaluated,coverage,live:liveMode(),secure:securePage()}}
function ensureStyles(){if($('#kcVerificationStyles'))return;const s=document.createElement('style');s.id='kcVerificationStyles';s.textContent=`.kc-evidence{grid-column:1/-1;font-size:10px;color:var(--muted);display:flex;gap:7px;align-items:center;flex-wrap:wrap}.kc-evidence button{border:0;background:transparent;color:var(--muted);padding:0;text-decoration:underline;text-underline-offset:2px}.kc-proof-modal{position:fixed;inset:0;z-index:60;background:rgba(2,6,14,.82);display:grid;place-items:center;padding:16px}.kc-proof-panel{width:min(620px,100%);max-height:88vh;overflow:auto;background:#0f1829;border:1px solid var(--line);border-radius:18px;padding:16px}.kc-proof-grid{display:grid;gap:9px;margin-top:12px}.kc-proof-row{display:grid;grid-template-columns:auto 1fr;gap:9px;padding:10px;border:1px solid var(--line);border-radius:12px;background:#0d1728}.kc-proof-dot{width:11px;height:11px;border-radius:50%;margin-top:4px}.kc-proof-dot.ok{background:var(--ok)}.kc-proof-dot.warn{background:var(--warn)}.kc-proof-note{margin-top:12px;padding:10px;border-left:3px solid var(--accent);background:#0d1728;color:var(--muted);font-size:11px;line-height:1.4}@media(max-width:620px){.kc-evidence{font-size:9px}.kc-proof-panel{border-radius:15px}}`;document.head.appendChild(s)}
async function openProof(){const s=state(),sec=await runtimeSecurity(),rows=[['Definierte Systemprüfungen',`${s.evaluated}/${s.defined} ausgewertet · ${s.coverage}% Prüfabdeckung`,s.coverage===100?'ok':'warn'],['LIVE-Monitoring',s.live?'Aktiver LIVE-Datenweg':'Kein LIVE-Datenweg aktiv',s.live?'ok':'warn'],['Transport',s.secure&&sec.https?'HTTPS für App und Prüf-API':'HTTPS-Abdeckung unvollständig',s.secure&&sec.https?'ok':'warn'],['Öffentliche Laufzeitkonfiguration',sec.publicOnly?'Kein offensichtlicher privilegierter Schlüssel erkannt':'Konfiguration prüfen',sec.publicOnly?'ok':'warn'],['Sicherheitsmethodik',`OWASP ASVS ${PROFILE.asvs} / WSTG ${PROFILE.wstg} als Prüforientierung`,'ok']];const modal=document.createElement('div');modal.className='kc-proof-modal';modal.id='kcProofModal';modal.innerHTML=`<div class="kc-proof-panel" role="dialog" aria-modal="true"><div class="row between"><div><div class="eyebrow">Prüfnachweis</div><h2>${PROFILE.name}</h2><div class="muted small">Profil ${PROFILE.version}</div></div><button class="secondary" id="kcProofClose">✕</button></div><div class="kc-proof-grid">${rows.map(r=>`<div class="kc-proof-row"><span class="kc-proof-dot ${r[2]}"></span><div><strong>${esc(r[0])}</strong><div class="muted small">${esc(r[1])}</div></div></div>`).join('')}</div><div class="kc-proof-note"><strong>Wichtig:</strong> 100% bedeutet 100% der definierten und aktuell messbaren Prüfungen bestanden. Es ist keine Garantie gegen unbekannte Fehler, nicht modellierte Geschäftslogikfehler oder noch nicht integrierte Sicherheitsprüfungen.</div></div>`;document.body.appendChild(modal);$('#kcProofClose').onclick=()=>modal.remove();modal.onclick=e=>{if(e.target===modal)modal.remove()}}
function render(){ensureStyles();const hero=$('.hero');if(!hero)return;let host=$('#kcEvidence');if(!host){host=document.createElement('div');host.id='kcEvidence';host.className='kc-evidence';hero.appendChild(host)}const s=state();host.innerHTML=`<span>Nachweis: ${s.evaluated}/${s.defined||0} definiert · ${s.coverage}% Prüfabdeckung${s.live?' · LIVE':''}</span><button type="button">Details</button>`;host.querySelector('button').onclick=openProof}
let queued=false;function schedule(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;render()})}
render();new MutationObserver(schedule).observe(document.documentElement,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['class','checked']});
