import{test,expect}from'@playwright/test';

const URL='http://127.0.0.1:4173/';

async function withPage(browser,viewport,fn){const context=await browser.newContext({viewport});const page=await context.newPage();try{await fn(page)}finally{await context.close()}}

test('Mobile 390x844 shell, One Touch and settings',async({browser})=>withPage(browser,{width:390,height:844},async page=>{await page.goto(URL);await expect(page.locator('.topbar h1')).toContainText('KC System Check');await expect(page.locator('#appVersion')).toContainText(/^v\d+\.\d+\.\d+$/);await expect(page.locator('#healthValue')).toBeVisible();await expect(page.locator('#oneTouchBtn')).toBeVisible();await expect(page.locator('.gauge-card')).toHaveCount(4);await page.locator('#oneTouchBtn').click();await expect(page.locator('#progressCard')).not.toHaveClass(/hidden/);await expect(page.locator('#oneTouchBtn')).toBeDisabled();await page.locator('#cancelBtn').click();const tabs=page.locator('.tabs');await expect(tabs).toBeVisible();expect(await tabs.evaluate(el=>el.scrollWidth>=el.clientWidth)).toBeTruthy();await page.locator('#settingsBtn').click();await expect(page.locator('#settingsModal')).not.toHaveClass(/hidden/);await expect(page.locator('#kcServerAlarmSettings')).toBeVisible()}));

test('Desktop 1440x900 wide layout and One Touch reacts',async({browser})=>withPage(browser,{width:1440,height:900},async page=>{await page.goto(URL);expect(await page.evaluate(()=>window.innerWidth)).toBe(1440);await expect(page.locator('#kcDesktopOverview')).toBeVisible();await expect(page.locator('.desktop-overview-card')).toHaveCount(5);await expect(page.locator('#kcDesktopHeroExtra')).toBeVisible();await expect(page.locator('.desktop-hero-extra-row')).toHaveCount(2);const systems=page.locator('#dashboard>.gauges+.card'),chart=page.locator('#dashboard>.gauges+.card+.card');await expect(systems).toBeVisible();await expect(chart).toBeVisible();const a=await systems.boundingBox(),b=await chart.boundingBox(),main=await page.locator('main').boundingBox();expect(a).toBeTruthy();expect(b).toBeTruthy();expect(main).toBeTruthy();expect(Math.abs(a.y-b.y)).toBeLessThan(8);expect(b.x).toBeGreaterThan(a.x+a.width-5);expect(main.width).toBeGreaterThan(1100);await page.locator('#oneTouchBtn').click();await expect(page.locator('#progressCard')).not.toHaveClass(/hidden/);await expect(page.locator('#oneTouchBtn')).toBeDisabled();await page.locator('#cancelBtn').click()}));
