import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';
test('release exposes version in header',()=>{const h=fs.readFileSync('index.html','utf8');assert.match(h,/id="appVersion"/);assert.match(h,/id="runtimeMode"/)});
test('mirror UI is mismatch based, not fake zero latency',()=>{const a=fs.readFileSync('js/app.js','utf8');assert.match(a,/mismatch_count/);assert.doesNotMatch(a,/gaugeMirror[^\n]+latency\|\|0/)});
test('daily automation is at most daily and no storage write',()=>{const y=fs.readFileSync('.github/workflows/daily-check.yml','utf8');assert.match(y,/cron: '20 5 \* \* \*'/);assert.doesNotMatch(y,/upload/i)});
test('free tier invocation estimate uses runs not provider requests',()=>{const a=fs.readFileSync('js/app.js','utf8');assert.match(a,/runs=Number\(u\.runs_31d/);assert.match(a,/providerRequests=Number\(u\.requests_31d/)});
test('capacity has 1 7 30 day windows',()=>{const a=fs.readFileSync('js/app.js','utf8');assert.match(a,/growthLabel\(hist,s\.id,1\)/);assert.match(a,/growthLabel\(hist,s\.id,7\)/);assert.match(a,/growthLabel\(hist,s\.id,30\)/)});
test('pages bundle contains every imported runtime module',()=>{const y=fs.readFileSync('.github/workflows/pages.yml','utf8');assert.match(y,/js\/usage\.js/);assert.match(y,/test -f dist\/js\/usage\.js/)});
test('service worker is network first and purges old app caches',()=>{const s=fs.readFileSync('sw.js','utf8');assert.match(s,/cache:\"no-store\"/);assert.match(s,/purgeOldCaches/);assert.match(s,/APP_PREFIX/);assert.match(s,/networkFirst/)});
test('health gauge uses high-is-good semantics',()=>{const a=fs.readFileSync('js/app.js','utf8'),g=fs.readFileSync('js/gauges.js','utf8');assert.match(a,/drawGauge\(\$\("#gaugeHealth"\),health,100,"Gesund",true\)/);assert.match(g,/goodHigh/)});
test('history deduplicates local and server runs',()=>{const a=fs.readFileSync('js/app.js','utf8');assert.match(a,/function sameRun/);assert.match(a,/rem\.some\(r=>sameRun\(l,r\)\)/)});
test('startup restores last-run label from remote history',()=>{const a=fs.readFileSync('js/app.js','utf8');assert.match(a,/function updateLastRunLabel/);assert.match(a,/updateLastRunLabel\(\)/)});
