const now=()=>new Date().toISOString();
const status=h=>h>=90?"ok":h>=70?"warn":"bad";
const result=(id,name,kind,health,detail,extra={})=>({id,name,kind,health,status:status(health),detail,checkedAt:now(),...extra});
async function timed(url,options={},timeout=5000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout),started=Date.now();try{const r=await fetch(url,{...options,signal:c.signal,cache:"no-store"});return{r,latency:Date.now()-started}}finally{clearTimeout(t)}}
async function supabase(env){if(!env.SUPABASE_URL||!env.SUPABASE_ANON_KEY)return result("supabase","Supabase","database",0,"Noch nicht konfiguriert");try{const{r,latency}=await timed(`${env.SUPABASE_URL.replace(/\/$/,"")}/rest/v1/`,{headers:{apikey:env.SUPABASE_ANON_KEY,Authorization:`Bearer ${env.SUPABASE_ANON_KEY}`,Accept:"application/json"}});return result("supabase","Supabase","database",r.ok?(latency>600?82:98):35,r.ok?"API erreichbar":`HTTP ${r.status}`,{latency,metrics:{http_status:r.status,latency_ms:latency}})}catch(e){return result("supabase","Supabase","database",15,e.name==="AbortError"?"Zeitüberschreitung":e.message)}}
async function neon(env){if(!env.NEON_HEALTH_URL)return result("neon","Neon","database",0,"Health-Endpunkt noch nicht konfiguriert");try{const{r,latency}=await timed(env.NEON_HEALTH_URL,{headers:env.NEON_HEALTH_TOKEN?{Authorization:`Bearer ${env.NEON_HEALTH_TOKEN}`}:{}});return result("neon","Neon","database",r.ok?(latency>700?82:98):35,r.ok?"Erreichbar":`HTTP ${r.status}`,{latency,metrics:{http_status:r.status,latency_ms:latency}})}catch(e){return result("neon","Neon","database",15,e.name==="AbortError"?"Zeitüberschreitung":e.message)}}
async function mirror(env){if(!env.MIRROR_STATUS_URL)return result("mirror","Spiegelung","replication",0,"Mirror-Status-Endpunkt noch nicht konfiguriert");try{const{r}=await timed(env.MIRROR_STATUS_URL,{headers:env.MIRROR_STATUS_TOKEN?{Authorization:`Bearer ${env.MIRROR_STATUS_TOKEN}`}:{}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const x=await r.json(),m=Number(x.mismatch_count||0),stale=Boolean(x.stale),h=m?45:stale?75:100;return result("mirror","Spiegelung","replication",h,m?`${m} Abweichung(en)`:stale?"Letzter Lauf zu alt":"Quelle und Ziel identisch",{metrics:{mismatch_count:m,last_success:x.last_success||null,stale}})}catch(e){return result("mirror","Spiegelung","replication",20,e.message)}}
async function b2(env){if(env.B2_CHECK_ENABLED!=="true")return{...result("b2","Backblaze B2","storage",100,"Nicht geprüft – B2-Check deaktiviert"),checked:false};return{...result("b2","Backblaze B2","storage",75,"B2-Lesecheck wird nach Secret-Konfiguration aktiviert"),checked:false}}
const adapters={supabase,neon,mirror,b2};
function cors(env,req){const origin=req.headers.get("Origin")||"";const allowed=env.ALLOWED_ORIGIN||"*";return{"access-control-allow-origin":allowed==="*"?"*":origin===allowed?origin:allowed,"access-control-allow-methods":"GET,OPTIONS","access-control-allow-headers":"content-type","cache-control":"no-store","content-type":"application/json; charset=utf-8"}}
export default{async fetch(req,env){const headers=cors(env,req);if(req.method==="OPTIONS")return new Response(null,{status:204,headers});const u=new URL(req.url);if(u.pathname==="/api/ping")return new Response(JSON.stringify({ok:true,version:"0.2.0",time:now()}),{headers});if(u.pathname!=="/api/check")return new Response(JSON.stringify({error:"not_found"}),{status:404,headers});const ids=(u.searchParams.get("systems")||Object.keys(adapters).join(",")).split(",").filter(x=>adapters[x]);const started=Date.now(),results=[];for(const id of ids)results.push(await adapters[id](env));const scored=results.filter(x=>x.checked!==false),health=scored.length?Math.round(scored.reduce((s,x)=>s+x.health,0)/scored.length*10)/10:0;return new Response(JSON.stringify({health,status:status(health),results,duration_ms:Date.now()-started,checkedAt:now()}),{headers})}}
