import{MonitoringAdapter}from"./base.js";

const ALLOWED_STATUS=new Set(["healthy","warning","critical","unknown","not_configured"]);
const FORBIDDEN_KEYS=new Set(["password","passwd","secret","token","access_key","access_key_id","application_key","api_key","dsn","recovery_key","private_key","original_path","decrypted_path","filename","file_name"]);

function normaliseStatus(value){const raw=String(value||"unknown").trim().toLowerCase();const aliases={ok:"healthy",success:"healthy",successful:"healthy",warn:"warning",failed:"critical",error:"critical",offline:"critical",disabled:"not_configured",running:"healthy",in_progress:"healthy",active:"healthy"};const mapped=aliases[raw]||raw;return ALLOWED_STATUS.has(mapped)?mapped:"unknown"}
function runningJob(snapshot){const job=snapshot?.currentJob||snapshot?.activeJob||snapshot?.runningJob||null;if(job&&["running","in_progress","active"].includes(String(job.status||"running").toLowerCase()))return job;const last=snapshot?.lastJob;if(last&&["running","in_progress","active"].includes(String(last.status||"").toLowerCase()))return last;return null}
function finite(v){const n=Number(v);return Number.isFinite(n)?n:null}

function assertNoSecrets(value,path="snapshot"){if(Array.isArray(value)){value.forEach((item,index)=>assertNoSecrets(item,`${path}[${index}]`));return}if(!value||typeof value!=="object")return;for(const[key,item]of Object.entries(value)){if(FORBIDDEN_KEYS.has(String(key).toLowerCase()))throw new Error(`Backup-Telemetrie enthält unzulässiges Feld: ${path}.${key}`);assertNoSecrets(item,`${path}.${key}`)}}

export function mapBackupVaultSnapshot(snapshot){if(!snapshot||typeof snapshot!=="object")throw new Error("Backup-Vault-Telemetrie fehlt");assertNoSecrets(snapshot);if(snapshot.sourceProgram!=="pc-backup-vault")throw new Error("Unbekannte Telemetriequelle");const targets=Array.isArray(snapshot.targets)?snapshot.targets:[];const critical=targets.filter(t=>normaliseStatus(t?.status)==="critical");const warnings=targets.filter(t=>normaliseStatus(t?.status)==="warning");const currentJob=runningJob(snapshot);let status=normaliseStatus(snapshot.status);if(critical.length)status="critical";else if(warnings.length&&status==="healthy")status="warning";else if(currentJob&&status==="unknown")status="healthy";let detail=currentJob?"Backup läuft":"Backup Vault Telemetrie verfügbar";if(critical.length)detail=`${critical.length} Speicherziel(e) kritisch`;else if(warnings.length)detail=`${warnings.length} Speicherziel(e) mit Warnung`;const progress=currentJob?{status:String(currentJob.status||"running"),startedAt:currentJob.startedAt||currentJob.started_at||null,updatedAt:currentJob.updatedAt||currentJob.updated_at||snapshot.generatedAt||null,processedBytes:finite(currentJob.processedBytes??currentJob.processed_bytes??currentJob.bytesDone??currentJob.bytes_done),totalBytes:finite(currentJob.totalBytes??currentJob.total_bytes??currentJob.bytesTotal??currentJob.bytes_total),bytesPerSecond:finite(currentJob.bytesPerSecond??currentJob.bytes_per_second??currentJob.bps),percent:finite(currentJob.percent??currentJob.progressPercent??currentJob.progress_percent),targetId:currentJob.targetId||currentJob.target_id||null}:null;return{id:"backup_vault",name:"PC Backup Vault",kind:"backup",status,health:status,latency:null,usage:snapshot.capacity?.usage??null,capacityLabel:snapshot.capacity?.label??null,detail,metrics:{generatedAt:snapshot.generatedAt||null,currentJob:progress,lastJob:snapshot.lastJob||{},lastVerify:snapshot.lastVerify||{},lastRestoreTest:snapshot.lastRestoreTest||{},targets}}}

export class BackupVaultAdapter extends MonitoringAdapter{constructor({loadSnapshot,enabled=true}={}){super({id:"backup_vault",name:"PC Backup Vault",kind:"backup",enabled});if(typeof loadSnapshot!=="function")throw new Error("loadSnapshot muss eine Funktion sein");this.loadSnapshot=loadSnapshot}async quickCheck(){return mapBackupVaultSnapshot(await this.loadSnapshot())}}
