import{MonitoringAdapter}from"./base.js";

const ALLOWED_STATUS=new Set(["healthy","warning","critical","unknown","not_configured"]);
const FORBIDDEN_KEYS=new Set(["password","passwd","secret","token","access_key","access_key_id","application_key","api_key","dsn","recovery_key","private_key","original_path","decrypted_path","filename","file_name"]);

function normaliseStatus(value){const raw=String(value||"unknown").trim().toLowerCase();const aliases={ok:"healthy",success:"healthy",successful:"healthy",warn:"warning",failed:"critical",error:"critical",offline:"critical",disabled:"not_configured"};const mapped=aliases[raw]||raw;return ALLOWED_STATUS.has(mapped)?mapped:"unknown"}

function assertNoSecrets(value,path="snapshot"){if(Array.isArray(value)){value.forEach((item,index)=>assertNoSecrets(item,`${path}[${index}]`));return}if(!value||typeof value!=="object")return;for(const[key,item]of Object.entries(value)){if(FORBIDDEN_KEYS.has(String(key).toLowerCase()))throw new Error(`Backup-Telemetrie enthält unzulässiges Feld: ${path}.${key}`);assertNoSecrets(item,`${path}.${key}`)}}

export function mapBackupVaultSnapshot(snapshot){if(!snapshot||typeof snapshot!=="object")throw new Error("Backup-Vault-Telemetrie fehlt");assertNoSecrets(snapshot);if(snapshot.sourceProgram!=="pc-backup-vault")throw new Error("Unbekannte Telemetriequelle");const targets=Array.isArray(snapshot.targets)?snapshot.targets:[];const critical=targets.filter(t=>normaliseStatus(t?.status)==="critical");const warnings=targets.filter(t=>normaliseStatus(t?.status)==="warning");let status=normaliseStatus(snapshot.status);if(critical.length)status="critical";else if(warnings.length&&status==="healthy")status="warning";let detail="Backup Vault Telemetrie verfügbar";if(critical.length)detail=`${critical.length} Speicherziel(e) kritisch`;else if(warnings.length)detail=`${warnings.length} Speicherziel(e) mit Warnung`;return{id:"backup_vault",name:"PC Backup Vault",kind:"backup",status,health:status,latency:null,usage:snapshot.capacity?.usage??null,capacityLabel:snapshot.capacity?.label??null,detail,metrics:{generatedAt:snapshot.generatedAt||null,lastJob:snapshot.lastJob||{},lastVerify:snapshot.lastVerify||{},lastRestoreTest:snapshot.lastRestoreTest||{},targets}}}

export class BackupVaultAdapter extends MonitoringAdapter{constructor({loadSnapshot,enabled=true}={}){super({id:"backup_vault",name:"PC Backup Vault",kind:"backup",enabled});if(typeof loadSnapshot!=="function")throw new Error("loadSnapshot muss eine Funktion sein");this.loadSnapshot=loadSnapshot}async quickCheck(){return mapBackupVaultSnapshot(await this.loadSnapshot())}}
