import{sanitizeDeep}from"../safe-html.js";
export async function loadRuntime(){for(const p of["./config/runtime.json","./config/runtime.public.json"]){try{const r=await fetch(p,{cache:"no-store"});if(r.ok){const cfg=await r.json();if(cfg?.apiBaseUrl)return cfg}}catch{}}return{apiBaseUrl:"",apiToken:"",apiStyle:"generic",mode:"demo"}}
function headersFor(runtime,direct){const headers={};if(runtime?.apiToken){headers.Authorization=`Bearer ${runtime.apiToken}`;if(direct)headers.apikey=runtime.apiToken}return headers}
function endpoint(runtime,path){const direct=runtime?.apiStyle==="supabase-edge",base=direct?runtime.apiBaseUrl:`${runtime.apiBaseUrl.replace(/\/$/,"")}${path}`;return{direct,base}}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function fetchJsonWithRetry(url,init,retries=2){let lastError;for(let attempt=0;attempt<=retries;attempt++){try{const r=await fetch(url,init);if(r.ok){const data=await r.json();if(data?.error)throw new Error(data.error);return data}if(![500,502,503,504,429].includes(r.status))throw new Error(`Prüf-API HTTP ${r.status}`);lastError=new Error(`Prüf-API HTTP ${r.status}`)}catch(e){if(e?.name==="AbortError")throw e;lastError=e}if(attempt<retries)await sleep(700*(attempt+1))}throw lastError||new Error("Prüf-API nicht erreichbar")}
export async function runLive(ids,runtime,{signal,trigger="manual",record=true}={}){if(!runtime?.apiBaseUrl)throw new Error("Prüf-API noch nicht konfiguriert");const selected=encodeURIComponent(ids.join(",")),{direct,base}=endpoint(runtime,"/api/check"),url=`${base}${base.includes("?")?"&":"?"}systems=${selected}&trigger=${encodeURIComponent(trigger)}&record=${record?1:0}`;return sanitizeDeep(await fetchJsonWithRetry(url,{cache:"no-store",headers:headersFor(runtime,direct),signal},2))}
export async function loadRemoteHistory(runtime){if(!runtime?.apiBaseUrl)return{history:[],usage:{}};const {direct,base}=endpoint(runtime,"/api/history"),url=`${base}${base.includes("?")?"&":"?"}history=1`;try{const r=await fetch(url,{cache:"no-store",headers:headersFor(runtime,direct)});if(!r.ok)return{history:[],usage:{}};return sanitizeDeep(await r.json())}catch{return{history:[],usage:{}}}}
export async function loadLeitstand(runtime,{signal}={}){if(!runtime?.apiBaseUrl)return{heartbeats:[],flows:[],sales:[],apps:[],error:"Leitstand-API nicht konfiguriert"};const {direct,base}=endpoint(runtime,"/api/leitstand"),url=`${base}${base.includes("?")?"&":"?"}leitstand=1`;try{const r=await fetch(url,{cache:"no-store",headers:headersFor(runtime,direct),signal});if(!r.ok)throw new Error(`Leitstand HTTP ${r.status}`);const data=await r.json();if(data?.error)throw new Error(data.error);return sanitizeDeep(data,{keepRaw:["error"]})}catch(e){return{heartbeats:[],flows:[],sales:[],apps:[],error:e.message||String(e)}}}
