create table if not exists public.kc_system_check_history (
  id bigint generated by default as identity primary key,
  checked_at timestamptz not null default now(),
  trigger_type text not null default 'manual' check (trigger_type in ('manual','auto','selected')),
  overall_status text not null,
  health integer,
  duration_ms integer,
  request_count integer not null default 0,
  response_bytes integer not null default 0,
  results jsonb not null default '[]'::jsonb
);
create index if not exists kc_system_check_history_checked_at_idx on public.kc_system_check_history (checked_at desc);
alter table public.kc_system_check_history enable row level security;
revoke all on public.kc_system_check_history from anon, authenticated;
comment on table public.kc_system_check_history is 'Kompakte Historie des KC System Check; Zugriff nur serverseitig ueber Edge Function.';
